Repository DragonOS-Community/DragonOS, pull requests merged in 2024-05, with the labels that each got.

#796 fix(mm):修复extract中对未映射到相应物理页的before after VMA的处理
  kernel/src/mm/ucontext.rs
Labels: Bug fix, S-等待审查

#801 feat(mm): 修复vma映射标志错误
  kernel/src/mm/fault.rs
  kernel/src/mm/ucontext.rs
Labels: enhancement, S-等待审查

#799 feat:(riscv/intr) 实现riscv plic驱动,能处理外部中断
  kernel/Cargo.toml
  kernel/crates/bitmap/src/alloc_bitmap.rs
  kernel/crates/bitmap/tests/alloc-bitmap.rs
  kernel/src/arch/riscv64/asm/bitops.rs
  kernel/src/arch/riscv64/driver/of.rs
  kernel/src/arch/riscv64/interrupt/entry.rs
  kernel/src/arch/riscv64/interrupt/handle.rs
  kernel/src/arch/riscv64/interrupt/mod.rs
  kernel/src/arch/riscv64/mm/mod.rs
  kernel/src/arch/x86_64/driver/apic/lapic_vector.rs
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/clocksource/timer_riscv.rs
  kernel/src/driver/irqchip/mod.rs
  kernel/src/driver/irqchip/riscv_intc.rs
  kernel/src/driver/irqchip/riscv_sifive_plic.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/virtio/irq.rs
  kernel/src/driver/virtio/mod.rs
  kernel/src/driver/virtio/sysfs.rs
  kernel/src/driver/virtio/transport.rs
  kernel/src/driver/virtio/transport_pci.rs
  kernel/src/exception/handle.rs
  kernel/src/exception/irqchip.rs
  kernel/src/exception/irqdata.rs
  kernel/src/exception/irqdesc.rs
  kernel/src/exception/irqdomain.rs
  kernel/src/exception/manage.rs
  kernel/src/libs/cpumask.rs
  kernel/src/mm/mmio_buddy.rs
  kernel/src/smp/cpu/mod.rs
Labels: enhancement, S-等待审查, A-driver, O-x86_64, O-riscv64, T-driver

#802 fix(mm):优化extract中对before和after VMA映射情况的判断
  kernel/src/mm/ucontext.rs
Labels: Bug fix, S-等待审查

#803 fix(mm):优化extract中对before和after VMA映射情况的判断 (#802)
  kernel/src/mm/ucontext.rs
Labels: Bug fix, S-等待审查

#804 feat(mm):添加MAP_FIXED处理
  kernel/src/mm/ucontext.rs
Labels: enhancement, S-等待审查

#806 feat(elf): [WIP] Dynamic link support
  build-scripts/.gitignore
  kernel/src/libs/elf.rs
  kernel/src/process/exec.rs
  user/apps/test_glibc/.gitignore
  user/apps/test_glibc/Cargo.toml
  user/apps/test_glibc/LICENSE
  user/apps/test_glibc/Makefile
  user/apps/test_glibc/README.md
  user/apps/test_glibc/src/main.rs
  user/dadk/config/glibc-2.39.9.dadk
  user/dadk/config/test_glibc-0.1.0.dadk
Labels: enhancement, S-等待审查

#807 docs(sched):调度子系统文档即cfs文档
  docs/kernel/sched/cfs.md
  docs/kernel/sched/core.md
Labels: documentation, S-等待审查, T-doc

#791 fix(net): Fix TCP Unresponsiveness and Inability to Close Connections
  kernel/src/net/net_core.rs
  kernel/src/net/socket/inet.rs
  kernel/src/net/socket/mod.rs
  user/apps/http_server/main.c
Labels: Bug fix, S-等待作者修改

#808 fix: disable mm debug log to prevent system lockup due to thingbuf issue
  kernel/src/debug/klog/mm.rs
  kernel/src/process/mod.rs
  user/dadk/config/held-0.1.0.dadk
Labels: Bug fix, S-等待审查

#809 chore(tools): add bootstrap support for Gentoo Linux
  tools/bootstrap.sh
Labels: documentation, S-等待审查

#792 feat(driver/pci): add pci bus into sysfs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/pci/attr.rs
  kernel/src/driver/pci/dev_id.rs
  kernel/src/driver/pci/device.rs
  kernel/src/driver/pci/driver.rs
  kernel/src/driver/pci/mod.rs
  kernel/src/driver/pci/pci.rs
  kernel/src/driver/pci/raw_device.rs
  kernel/src/driver/pci/subsys.rs
  kernel/src/driver/pci/test/mod.rs
  kernel/src/driver/pci/test/pt_device.rs
  kernel/src/driver/pci/test/pt_driver.rs
Labels: enhancement, S-等待审查, T-driver

#815 fix(driver/apic_timer): 修复local apic timer初始化顺序导致的在某些云服务器上无法收到中断的bug
  kernel/src/arch/x86_64/driver/apic/apic_timer.rs
Labels: S-等待审查, O-x86_64, T-driver

#821 fix(log): 修复pr #814 的问题
  kernel/crates/unified-init/src/lib.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/libs/printk.rs
Labels: Bug fix, S-等待审查, A-fs

#818 feat(driver/pci): 完善pci root结构体，增加portio的pci配置空间访问
  kernel/src/arch/x86_64/pci/pci.rs
  kernel/src/driver/pci/ecam.rs
  kernel/src/driver/pci/pci.rs
  kernel/src/driver/pci/root.rs
Labels: enhancement, S-等待审查, O-x86_64, O-riscv64, T-driver

#826 chore(tools): change the rust download mirror
  tools/change_rust_src.sh
Labels: S-等待审查

#830 fix(time):修复了issue #816内核时间子系统调用有误的bug
  kernel/src/time/timekeeping.rs
Labels: Bug fix, S-等待审查

#827 chore(tools): add the gentoo grub_auto_install support
  tools/grub_auto_install.sh
Labels: S-等待审查

#831 feat(procfs): update procfs
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/process/mod.rs
Labels: enhancement, S-等待审查, A-fs

#837 feat(mm): 修复mmap未延迟分配内存的问题
  kernel/src/arch/x86_64/interrupt/trap.rs
  kernel/src/mm/page.rs
  kernel/src/mm/syscall.rs
  kernel/src/mm/ucontext.rs
Labels: enhancement, O-x86_64, O-riscv64, A-fs, T-virtulization, T-driver

#833 fix(driver): fix memory security problem in tty device ioctl
  kernel/src/driver/tty/tty_device.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/net/event_poll/mod.rs
Labels: Bug fix, S-等待审查, A-fs, T-driver
