Repository DragonOS-Community/DragonOS, pull requests merged in 2024-09, with the labels that each got.

#903 feat: 添加gendisk抽象
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/base/block/disk_info.rs
  kernel/src/driver/base/block/gendisk.rs
  kernel/src/driver/base/block/manager.rs
  kernel/src/driver/base/block/mod.rs
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/disk/ahci/ahcidisk.rs
  kernel/src/driver/disk/ahci/mod.rs
  kernel/src/driver/mod.rs
  kernel/src/driver/scsi/mod.rs
  kernel/src/driver/virtio/irq.rs
  kernel/src/filesystem/fat/bpb.rs
  kernel/src/filesystem/fat/entry.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/mbr.rs
  kernel/src/filesystem/vfs/core.rs
  kernel/src/init/initial_kthread.rs
Labels: enhancement, A-driver, A-fs

#909 feat: add netlink_recv and netlink_send, fix bind and updates test
  kernel/src/net/socket/endpoint.rs
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/netlink/netlink.rs
  kernel/src/net/socket/netlink/skbuff.rs
  user/apps/test-uevent/src/main.rs
Labels: enhancement

#840 feat(mm): 简单实现fat文件系统的文件映射
  kernel/Cargo.toml
  kernel/src/arch/riscv64/mm/mod.rs
  kernel/src/arch/x86_64/kvm/vmx/ept.rs
  kernel/src/arch/x86_64/kvm/vmx/mmu.rs
  kernel/src/arch/x86_64/mm/fault.rs
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/arch/x86_64/mm/pkru.rs
  kernel/src/driver/net/dma.rs
  kernel/src/driver/video/mod.rs
  kernel/src/driver/virtio/virtio_impl.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/ipc/shm.rs
  kernel/src/ipc/syscall.rs
  kernel/src/libs/mod.rs
  kernel/src/libs/name.rs
  kernel/src/mm/allocator/page_frame.rs
  kernel/src/mm/c_adapter.rs
  kernel/src/mm/fault.rs
  kernel/src/mm/init.rs
  kernel/src/mm/kernel_mapper.rs
  kernel/src/mm/madvise.rs
  kernel/src/mm/mmio_buddy.rs
  kernel/src/mm/mod.rs
  kernel/src/mm/no_init.rs
  kernel/src/mm/page.rs
  kernel/src/mm/syscall.rs
  kernel/src/mm/ucontext.rs
  kernel/src/sched/mod.rs
  kernel/src/syscall/mod.rs
  kernel/src/virt/kvm/host_mem.rs
  user/apps/test_filemap/.gitignore
  user/apps/test_filemap/Makefile
  user/apps/test_filemap/main.c
  user/dadk/config/test_filemap-0.1.0.dadk
Labels: enhancement, S-等待作者修改, A-driver, O-x86_64, O-riscv64, A-fs, T-virtulization, T-driver

#913 feat: 添加对内核引导协议的抽象
  .vscode/settings.json
  docs/kernel/boot/bootloader.md
  docs/kernel/boot/index.rst
  docs/kernel/boot/multiboot2.md
  kernel/Cargo.toml
  kernel/src/arch/riscv64/driver/sbi.rs
  kernel/src/arch/riscv64/init/boot.rs
  kernel/src/arch/riscv64/init/dragonstub.rs
  kernel/src/arch/riscv64/init/mod.rs
  kernel/src/arch/riscv64/rand.rs
  kernel/src/arch/x86_64/asm/head.S
  kernel/src/arch/x86_64/init/boot.rs
  kernel/src/arch/x86_64/init/mod.rs
  kernel/src/arch/x86_64/init/multiboot2.rs
  kernel/src/arch/x86_64/link.lds
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/arch/x86_64/pci/pci.rs
  kernel/src/driver/Makefile
  kernel/src/driver/acpi/Makefile
  kernel/src/driver/acpi/acpi.c
  kernel/src/driver/acpi/acpi.h
  kernel/src/driver/acpi/c_adapter.rs
  kernel/src/driver/acpi/mod.rs
  kernel/src/driver/multiboot2/Makefile
  kernel/src/driver/multiboot2/multiboot2.c
  kernel/src/driver/multiboot2/multiboot2.h
  kernel/src/driver/video/fbdev/vesafb.rs
  kernel/src/driver/video/mod.rs
  kernel/src/include/bindings/wrapper.h
  kernel/src/init/boot.rs
  kernel/src/init/init.rs
  kernel/src/init/mod.rs
  kernel/src/libs/lib_ui/screen_manager.rs
  kernel/src/mm/c_adapter.rs
  kernel/src/mm/mm.h
  kernel/src/mm/mmio_buddy.rs
  kernel/src/mm/page.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/syscall/syscall.c
  kernel/src/time/sleep.h
  kernel/src/time/sleep.rs
  user/apps/test_gettimeofday/main.c
Labels: enhancement, T-doc, A-driver, O-x86_64, O-riscv64

#881 fix(virtio):修复了特定virtio设备环境下中断号重复错误，以及开机内核panic的bug
  kernel/src/driver/virtio/transport_pci.rs
  tools/run-qemu.sh
Labels: Bug fix, S-等待审查, A-driver, O-x86_64, A-fs

#914 feat: 允许通过multiboot引导（直到acpi初始化报错）
  kernel/Cargo.toml
  kernel/crates/multiboot/Cargo.toml
  kernel/crates/multiboot/src/lib.rs
  kernel/src/arch/x86_64/asm/head.S
  kernel/src/arch/x86_64/init/boot.rs
  kernel/src/arch/x86_64/init/mod.rs
  kernel/src/arch/x86_64/init/multiboot.rs
  kernel/src/arch/x86_64/init/multiboot2.rs
  kernel/src/arch/x86_64/link.lds
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/driver/video/fbdev/base/mod.rs
  kernel/src/init/boot.rs
Labels: enhancement, A-driver, O-x86_64

#915 fix(mm): 修复riscv64启动时的PageFault
  kernel/src/mm/page.rs
  kernel/src/mm/ucontext.rs
Labels: Bug fix

#916 feat: 初步实现Unix stream socket
  .vscode/settings.json
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
Labels: enhancement

#917 feat: first time could be compiled
  .vscode/settings.json
  kernel/src/driver/net/mod.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/common/shutdown.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  kernel/src/syscall/mod.rs
Labels: enhancement

#918 wip: boot to novashell started
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/arch/x86_64/syscall/nr.rs
  kernel/src/driver/acpi/sysfs.rs
  kernel/src/driver/base/uevent/kobject_uevent.rs
  kernel/src/driver/net/e1000e/e1000e_driver.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/common/mod.rs
  kernel/src/net/socket/common/poll_unit.rs
  kernel/src/net/socket/common/shutdown.rs
  kernel/src/net/socket/define/mod.rs
  kernel/src/net/socket/define/msg_flag.rs
  kernel/src/net/socket/define/option.rs
  kernel/src/net/socket/define/option_level.rs
  kernel/src/net/socket/endpoint.rs
  kernel/src/net/socket/family.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/common/port.rs
  kernel/src/net/socket/inet/datagram/inner.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inet/syscall.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/netlink/callback.rs
  kernel/src/net/socket/netlink/endpoint.rs
  kernel/src/net/socket/netlink/mod.rs
  kernel/src/net/socket/netlink/netlink.rs
  kernel/src/net/socket/netlink/netlink_proto.rs
  kernel/src/net/socket/netlink/skbuff.rs
  kernel/src/net/socket/netlink/sock.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/socket/utils.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  kernel/src/process/mod.rs
  kernel/src/syscall/mod.rs
Labels: ambiguous

#919 feat(driver/net): 将网络设备注册到sysfs, 添加设备类属性文件
  kernel/src/arch/x86_64/driver/rtc.rs
  kernel/src/driver/base/cpu.rs
  kernel/src/driver/base/device/bus.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/kobject.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/base/platform/subsys.rs
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/disk/ahci/ahcidisk.rs
  kernel/src/driver/input/ps2_mouse/ps_mouse_device.rs
  kernel/src/driver/input/serio/i8042/i8042_device.rs
  kernel/src/driver/input/serio/i8042/i8042_ports.rs
  kernel/src/driver/input/serio/i8042/mod.rs
  kernel/src/driver/net/class.rs
  kernel/src/driver/net/e1000e/e1000e_driver.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/driver/net/sysfs.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/pci/device.rs
  kernel/src/driver/pci/raw_device.rs
  kernel/src/driver/pci/subsys.rs
  kernel/src/driver/pci/test/pt_device.rs
  kernel/src/driver/rtc/sysfs.rs
  kernel/src/driver/serial/serial8250/mod.rs
  kernel/src/driver/tty/tty_device.rs
  kernel/src/driver/video/fbdev/base/fbcon/mod.rs
  kernel/src/driver/video/fbdev/base/fbmem.rs
  kernel/src/driver/video/fbdev/vesafb.rs
  kernel/src/driver/virtio/mmio.rs
  kernel/src/driver/virtio/mod.rs
  kernel/src/driver/virtio/sysfs.rs
  kernel/src/driver/virtio/virtio.rs
  kernel/src/net/net_core.rs
Labels: enhancement, A-network

#920 初版Seqpacket socket
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
Labels: A-network

#921 feat(net):完善socket_pair实现，网络重构初步进入系统
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/syscall.rs
Labels: enhancement

#924 add accept blocking operation
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/common/epoll_items.rs
  kernel/src/net/socket/common/mod.rs
  kernel/src/net/socket/common/poll_unit.rs
  kernel/src/net/socket/define/mod.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inet/syscall.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/mod.rs
Labels: ambiguous

#926 feat(net): Temporarily completed user space testing of netlink/uevent
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/netlink/endpoint.rs
  kernel/src/net/socket/netlink/mod.rs
  kernel/src/net/socket/netlink/netlink_diag.rs
  kernel/src/net/socket/netlink/netlink_socket.rs
  kernel/src/net/socket/utils.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  user/apps/test-uevent/src/main.rs
  user/dadk/config/cloud-seed-0.1.0.dadk
Labels: enhancement

#929 feat(net):建立Unix InodeID映射表，并完善seqpacket相关功能
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/endpoint.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  user/apps/test_seqpacket/.gitignore
  user/apps/test_seqpacket/Cargo.toml
  user/apps/test_seqpacket/Makefile
  user/apps/test_seqpacket/README.md
  user/apps/test_seqpacket/src/main.rs
  user/apps/test_seqpacket/src/seq_pair.rs
  user/apps/test_seqpacket/src/seq_socket.rs
  user/dadk/config/test_seqpacket_0_1_0.dadk
Labels: enhancement

#930 feat(net): 实现阻塞式unix stream socket 读写机制
  .vscode/settings.json
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/socket/utils.rs
  kernel/src/net/syscall.rs
  kernel/src/syscall/user_access.rs
  user/apps/test_unix_stream_socket/.gitignore
  user/apps/test_unix_stream_socket/Cargo.toml
  user/apps/test_unix_stream_socket/Makefile
  user/apps/test_unix_stream_socket/README.md
  user/apps/test_unix_stream_socket/src/main.rs
  user/dadk/config/test_stream_socket_0_1_0.dadk
Labels: enhancement

#931 Feature/network-syscall
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/unix/mod.rs
Labels: ambiguous

#933 fix: udp & loopback “勉强能用”
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/driver/net/e1000e/e1000e_driver.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/datagram/inner.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/syscall.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  kernel/src/syscall/mod.rs
  user/apps/test_lo/src/main.rs
Labels: Bug fix

#935 ci(docs): Build docs when push/PR to master and release version.
  .github/workflows/docs-multiversion.yml
  .github/workflows/docs.yml
  docs/Makefile
  docs/_templates/versions.html
  docs/conf.py
  docs/requirements.txt
Labels: T-doc

#928 fix: Fix make update-submodules-by-mirror Error
  Makefile
Labels: Bug fix

#934 feat(ida): IDA内部改为使用XArray实现
  docs/kernel/libs/id-allocation.md
  docs/kernel/libs/index.rst
  kernel/Cargo.toml
  kernel/crates/ida/Cargo.toml
  kernel/crates/ida/README.md
  kernel/crates/ida/src/lib.rs
  kernel/crates/kdepends/Cargo.toml
  kernel/crates/kdepends/src/lib.rs
  kernel/src/debug/klog/mm.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/rtc/sysfs.rs
  kernel/src/driver/virtio/sysfs.rs
  kernel/src/filesystem/devpts/mod.rs
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/ipc/shm.rs
  kernel/src/lib.rs
  kernel/src/libs/ida/src/lib.rs
  kernel/src/mm/ucontext.rs
  kernel/src/net/socket/handle.rs
Labels: enhancement, T-doc, A-driver, A-fs

#941 feat(net): 调试现有函数调用链条，完善部分设计，为下一步继续实现udev监听并关联sysfs节点做准备
  kernel/src/driver/base/kobject.rs
  kernel/src/driver/base/uevent/kobject_uevent.rs
  kernel/src/driver/base/uevent/mod.rs
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/netlink/mod.rs
  kernel/src/net/socket/netlink/netlink.rs
  kernel/src/net/socket/netlink/skbuff.rs
Labels: enhancement

#938 feat(net):完善Unix Endpoint,实现Unix socket的地址转换
  kernel/src/net/socket/endpoint.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/syscall_util.rs
  user/apps/test_seqpacket/src/seq_socket.rs
  user/apps/test_unix_stream_socket/src/main.rs
Labels: enhancement

#943 can http_server and test_lo
  .vscode/settings.json
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/syscall_util.rs
Labels: S-等待审查, A-driver, O-x86_64, A-fs, ambiguous

#946 fix(kbd): 修复键盘命令解析器生成的字节码与Linux不一致的问题
  kernel/src/libs/keyboard_parser.rs
  user/dadk/config/nova_shell-0.1.0.dadk
Labels: Bug fix, S-等待审查

#925 feat(union filesystem): add overlay filesystem
  kernel/src/arch/x86_64/process/mod.rs
  kernel/src/filesystem/mod.rs
  kernel/src/filesystem/overlayfs/copy_up.rs
  kernel/src/filesystem/overlayfs/entry.rs
  kernel/src/filesystem/overlayfs/mod.rs
  kernel/src/namespace/mnt_namespace.rs
  kernel/src/namespace/mod.rs
  kernel/src/namespace/namespace.rs
  kernel/src/namespace/pid_namespace.rs
  kernel/src/namespace/syscall.rs
  kernel/src/namespace/ucount.rs
  kernel/src/namespace/user_namespace.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  kernel/src/process/syscall.rs
  kernel/src/syscall/mod.rs
  user/apps/test_namespace/Cargo.toml
  user/apps/test_namespace/Makefile
  user/apps/test_namespace/makefile.toml
  user/apps/test_namespace/src/main.rs
  user/dadk/config/test_namespace.dadk
Labels: O-x86_64, A-fs
