Repository DragonOS-Community/DragonOS, pull requests merged in 2024-07, with the labels that each got.

#842 feat: network-syscall dev branch
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/arch/x86_64/syscall/nr.rs
  kernel/src/net/mod.rs
  kernel/src/net/socket/define.rs
  kernel/src/net/socket/inet.rs
  kernel/src/net/socket/ip_def.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/tcp_def.rs
  kernel/src/net/syscall.rs
  user/dadk/config/cloud-seed-0.1.0.dadk
  user/sysconfig/home/reach/system/cloud-seed.service
Labels: enhancement

#847 fix(mm): 修复mprotect系统调用未正确设置vm_flags的错误
  kernel/src/mm/ucontext.rs
Labels: Bug fix

#836 fix(time): modify update wall time
  kernel/src/arch/x86_64/driver/apic/apic_timer.rs
  kernel/src/arch/x86_64/driver/hpet.rs
  kernel/src/driver/clocksource/acpi_pm.rs
  kernel/src/driver/clocksource/timer_riscv.rs
  kernel/src/time/clocksource.rs
  kernel/src/time/jiffies.rs
  kernel/src/time/mod.rs
  kernel/src/time/tick_common.rs
  kernel/src/time/timekeep.rs
  kernel/src/time/timekeeping.rs
  kernel/src/time/timer.rs
Labels: Bug fix, S-等待审查, O-x86_64, T-driver

#849 doc: 完善README.md
  README.md
  README_EN.md
Labels: A-meta

#850 chore: 更新sphinx相关配置，适应read the docs的更新
  docs/conf.py
Labels: documentation

#845 feat(driver/net): 实现Loopback网卡接口
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/net/net_core.rs
  user/apps/test_lo/.gitignore
  user/apps/test_lo/Cargo.toml
  user/apps/test_lo/Makefile
  user/apps/test_lo/README.md
  user/apps/test_lo/src/main.rs
  user/dadk/config/test_lo_0_1_0.dadk
Labels: enhancement, S-等待审查, A-driver, T-driver

#858 feat(fs): add eventfd syscall support
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/mod.rs
  kernel/src/syscall/mod.rs
  user/apps/test_eventfd/.gitignore
  user/apps/test_eventfd/Makefile
  user/apps/test_eventfd/main.c
  user/dadk/config/test_eventfd_0_1_0.dadk
Labels: enhancement, A-fs

#870 fix: 修复由于升级到2024-07-23工具链之后，某些机器上面内核运行一直fault的问题。
  Makefile
  kernel/.cargo/config.toml
  kernel/Makefile
  kernel/env.mk
  kernel/src/arch/riscv64/process/syscall.rs
  kernel/src/arch/x86_64/process/syscall.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/process/exec.rs
  kernel/src/process/mod.rs
  kernel/src/process/syscall.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/user_access.rs
Labels: Bug fix
