Repository DragonOS-Community/DragonOS, pull requests merged in 2024-10, with the labels that each got.

#951 修复vnc启动失败的问题
  tools/run-qemu.sh
Labels: ambiguous

#955 fix: 修复root用户信息未正确换行的问题
  user/sysconfig/etc/group
  user/sysconfig/etc/gshadow
  user/sysconfig/etc/passwd
  user/sysconfig/etc/shadow
Labels: Bug fix

#952 feat(tty): 实现发送SIGINT终止信号
  kernel/src/driver/tty/tty_job_control.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  user/apps/test_sigint/.gitignore
  user/apps/test_sigint/Makefile
  user/apps/test_sigint/main.c
  user/dadk/config/nova_shell-0.1.0.dadk
  user/dadk/config/test_sigint-0.1.0.dadk
Labels: enhancement

#957 fix(driver/net): 修复iface设备无法中断的bug
  kernel/src/driver/net/virtio_net.rs
Labels: Bug fix, A-network

#958 完善unix socket的poll方法，并解决test_socket死锁问题
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/syscall_util.rs
  user/apps/test_seqpacket/src/seq_socket.rs
Labels: ambiguous

#932 feat: 释放slab中的空闲页面到buddy
  kernel/crates/rust-slabmalloc/src/lib.rs
  kernel/crates/rust-slabmalloc/src/pages.rs
  kernel/crates/rust-slabmalloc/src/sc.rs
  kernel/crates/rust-slabmalloc/src/zone.rs
  kernel/src/mm/allocator/kernel_allocator.rs
  kernel/src/mm/allocator/slab.rs
Labels: enhancement, S-等待作者修改

#972 ci: add-bpf-linker-to-ci-image
  .github/workflows/makefile.yml
  tools/BUILD_CONTAINER_VERSION
  tools/bootstrap.sh
Labels: S-等待审查

#968 feat(tty): 将tty设备适配epoll，修改串口部分问题
  kernel/src/driver/serial/serial8250/serial8250_pio.rs
  kernel/src/driver/tty/termios.rs
  kernel/src/driver/tty/tty_core.rs
  kernel/src/driver/tty/tty_port.rs
  kernel/src/driver/tty/virtual_terminal/mod.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/ipc/pipe.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/net/net_core.rs
Labels: enhancement, A-driver, A-fs

#969 feat(boot): 内核启动命令行参数解析
  docs/kernel/boot/cmdline.md
  docs/kernel/boot/index.rst
  kernel/Cargo.toml
  kernel/crates/kcmdline_macros/Cargo.toml
  kernel/crates/kcmdline_macros/src/lib.rs
  kernel/src/driver/tty/tty_core.rs
  kernel/src/filesystem/vfs/core.rs
  kernel/src/init/boot.rs
  kernel/src/init/cmdline.rs
  kernel/src/init/init.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/init/mod.rs
  kernel/src/lib.rs
  kernel/src/libs/lib_ui/textui.rs
  tools/write_disk_image.sh
Labels: enhancement, T-doc, A-driver, A-fs

#973 feat: 支持 sysfs下 block, char, Net, rtc, tty 等类型设备的 uevent 文件读操作
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/kobject.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/base/uevent/mod.rs
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/net/class.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/pci/raw_device.rs
  kernel/src/driver/pci/test/pt_device.rs
  kernel/src/driver/rtc/class.rs
  kernel/src/driver/rtc/sysfs.rs
  kernel/src/driver/tty/sysfs.rs
  kernel/src/driver/video/fbdev/base/fbcon/mod.rs
  kernel/src/driver/video/fbdev/base/fbmem.rs
  kernel/src/exception/sysfs.rs
Labels: enhancement, A-driver, O-x86_64

#974 clean format, enable ctrl-c in accept blocking
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/base/uevent/mod.rs
  kernel/src/driver/net/mod.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inet/syscall.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  user/apps/ping/src/ping.rs
  user/apps/test-uevent/src/main.rs
  user/apps/test_seqpacket/src/main.rs
  user/apps/test_seqpacket/src/seq_pair.rs
  user/apps/test_seqpacket/src/seq_socket.rs
  user/apps/test_unix_stream_socket/src/main.rs
Labels: S-等待审查, A-driver, O-x86_64, ambiguous

#976 feat: merge master and ready for pr in master
  .github/workflows/makefile.yml
  docs/kernel/boot/cmdline.md
  docs/kernel/boot/index.rst
  kernel/Cargo.toml
  kernel/crates/kcmdline_macros/Cargo.toml
  kernel/crates/kcmdline_macros/src/lib.rs
  kernel/crates/rust-slabmalloc/src/lib.rs
  kernel/crates/rust-slabmalloc/src/pages.rs
  kernel/crates/rust-slabmalloc/src/sc.rs
  kernel/crates/rust-slabmalloc/src/zone.rs
  kernel/src/driver/serial/serial8250/serial8250_pio.rs
  kernel/src/driver/tty/termios.rs
  kernel/src/driver/tty/tty_core.rs
  kernel/src/driver/tty/tty_port.rs
  kernel/src/driver/tty/virtual_terminal/mod.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/vfs/core.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/init/boot.rs
  kernel/src/init/cmdline.rs
  kernel/src/init/init.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/init/mod.rs
  kernel/src/ipc/pipe.rs
  kernel/src/lib.rs
  kernel/src/libs/lib_ui/textui.rs
  kernel/src/mm/allocator/kernel_allocator.rs
  kernel/src/mm/allocator/slab.rs
  kernel/src/net/event_poll/mod.rs
  tools/BUILD_CONTAINER_VERSION
  tools/bootstrap.sh
  tools/write_disk_image.sh
Labels: enhancement, A-network

#979 fix: 修复启动时panic的错误
  kernel/src/driver/video/mod.rs
Labels: Bug fix, S-等待审查, A-driver

#980 remove(uevent): 将 netlink/uevent 机制从网络子分支中暂时移除
  kernel/src/driver/acpi/sysfs.rs
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/base/device/driver.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/kobject.rs
  kernel/src/driver/base/kset.rs
  kernel/src/driver/base/mod.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/base/uevent/kobject_uevent.rs
  kernel/src/driver/base/uevent/mod.rs
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/net/class.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/pci/raw_device.rs
  kernel/src/driver/pci/test/pt_device.rs
  kernel/src/driver/rtc/class.rs
  kernel/src/driver/rtc/sysfs.rs
  kernel/src/driver/tty/sysfs.rs
  kernel/src/driver/video/fbdev/base/fbcon/mod.rs
  kernel/src/driver/video/fbdev/base/fbmem.rs
  kernel/src/exception/sysfs.rs
  kernel/src/net/socket/endpoint.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/netlink/callback.rs
  kernel/src/net/socket/netlink/endpoint.rs
  kernel/src/net/socket/netlink/mod.rs
  kernel/src/net/socket/netlink/netlink.rs
  kernel/src/net/socket/netlink/netlink_proto.rs
  kernel/src/net/socket/netlink/skbuff.rs
  kernel/src/net/socket/netlink/sock.rs
  kernel/src/net/socket/utils.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  user/apps/test-uevent/.cargo/config.toml
  user/apps/test-uevent/.gitignore
  user/apps/test-uevent/Cargo.toml
  user/apps/test-uevent/Makefile
  user/apps/test-uevent/README.md
  user/apps/test-uevent/src/main.rs
  user/dadk/config/test_uevent_0_1_0.dadk
Labels: S-等待审查, A-driver, ambiguous

#986 feat: 添加SYS_MKDIRAT系统调用
  kernel/src/filesystem/vfs/core.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
Labels: enhancement, S-等待审查, A-fs

#988 feat: remove syscall prettier printing
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/arch/x86_64/syscall/nr.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/common/epoll_items.rs
  kernel/src/net/socket/common/mod.rs
  kernel/src/net/socket/define/option_level.rs
  kernel/src/net/socket/define/tmp.rs
  kernel/src/net/socket/family.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/mod.rs
  kernel/src/net/socket/inet/posix/option.rs
  kernel/src/net/socket/inet/posix/proto.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inet/stream/option.rs
  kernel/src/net/socket/inet/syscall.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/posix/mod.rs
  kernel/src/net/socket/posix/msg_flag.rs
  kernel/src/net/socket/posix/option.rs
  kernel/src/net/socket/posix/option_level.rs
  kernel/src/net/socket/posix/types.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/mod.rs
  kernel/src/net/socket/utils.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
Labels: enhancement, S-等待审查, A-driver, O-x86_64, A-fs

#995 去除virtio_blk, virtio_net expect错误处理，直接返回错误
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/net/virtio_net.rs
Labels: S-等待审查, A-driver, ambiguous

#985 fix: 临时修复线程退出时处理tty前台进程组产生panic的bug
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
Labels: Bug fix, S-等待审查

#996 fix: 修复网卡顺序的bug
  kernel/src/driver/net/e1000e/e1000e_driver.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/inet/common/mod.rs
Labels: Bug fix, S-等待作者修改, A-driver

#1002 doc: 修正开发者参与指南的链接
  docs/Makefile
  docs/community/code_contribution/index.rst
  docs/community/code_contribution/the-development-process.md
  docs/community/contact/index.rst
  triagebot.toml
Labels: S-等待审查, T-doc, A-meta

#1003 doc: update ringotek message
  docs/community/contact/index.rst
Labels: S-等待审查, T-doc

#1006 chore: Update NovaShell to 7bb802ad1e
  user/dadk/config/nova_shell-0.1.0.dadk
Labels: S-等待审查

#1010 fix(tools):支持在无kvm支持下运行DragonOS
  tools/run-qemu.sh
Labels: Bug fix

#1012 ci: 删除PR #948 代入的cache-toolchain.toml
  .github/workflows/cache-toolchain.yml
Labels: S-等待审查

#1013 fix: tty刷新线程初始化之前，键盘产生数据导致崩溃的问题
  kernel/src/driver/tty/kthread.rs
Labels: Bug fix, S-等待审查, A-driver

#1014 fix: 临时修复键盘驱动与鼠标驱动冲突导致键盘无响应
  kernel/Cargo.toml
  kernel/src/arch/x86_64/asm/entry.S
  kernel/src/driver/input/mod.rs
  kernel/src/driver/input/serio/i8042/mod.rs
  kernel/src/driver/keyboard/ps2_keyboard.rs
Labels: Bug fix, S-等待审查, A-driver, O-x86_64

#1015 fix(tty): 修复tty对tab进行处理时产生数组越界panic的问题
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/libs/font/mod.rs
Labels: Bug fix, S-等待审查, A-driver

#1016 chore: 修改traigebot配置（关于sig-obs & Test）
  triagebot.toml
Labels: S-等待审查, A-meta

#962 feat:添加chown系统调用
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/process/cred.rs
  kernel/src/syscall/mod.rs
  user/apps/test-chown/.gitignore
  user/apps/test-chown/Cargo.toml
  user/apps/test-chown/Makefile
  user/apps/test-chown/README.md
  user/apps/test-chown/src/main.rs
  user/dadk/config/test_chown_0_1_0.dadk
Labels: enhancement, S-等待作者修改, T-doc, A-driver, A-fs

#1017 feat(net): 实现unix抽象地址空间
  kernel/src/net/posix.rs
  kernel/src/net/socket/endpoint.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/socket/unix/ns/abs.rs
  kernel/src/net/socket/unix/ns/mod.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
  user/apps/test_unix_stream_socket/src/main.rs
Labels: enhancement, Done, A-network

#1018 fix(driver/virtio): 修改pci transport中断初始化的位置
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/virtio/transport.rs
  kernel/src/driver/virtio/transport_pci.rs
  kernel/src/net/net_core.rs
Labels: Bug fix

#949 ospp project (feature) add namespace overlayfs cgroup
  docs/index.rst
  docs/kernel/container/index.rst
  docs/kernel/container/namespaces/index.rst
  docs/kernel/container/namespaces/mnt_namespace.md
  docs/kernel/container/namespaces/pid_namespace.md
  docs/kernel/filesystem/index.rst
  docs/kernel/filesystem/unionfs/index.rst
  docs/kernel/filesystem/unionfs/overlayfs.md
  kernel/crates/ida/src/lib.rs
  kernel/src/arch/riscv64/process/mod.rs
  kernel/src/arch/x86_64/process/mod.rs
  kernel/src/cgroup/mem_cgroup.rs
  kernel/src/cgroup/mod.rs
  kernel/src/filesystem/mod.rs
  kernel/src/filesystem/overlayfs/copy_up.rs
  kernel/src/filesystem/overlayfs/entry.rs
  kernel/src/filesystem/overlayfs/mod.rs
  kernel/src/filesystem/ramfs/mod.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/lib.rs
  kernel/src/libs/ida/src/lib.rs
  kernel/src/namespaces/mnt_namespace.rs
  kernel/src/namespaces/mod.rs
  kernel/src/namespaces/namespace.rs
  kernel/src/namespaces/pid_namespace.rs
  kernel/src/namespaces/syscall.rs
  kernel/src/namespaces/ucount.rs
  kernel/src/namespaces/user_namespace.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  kernel/src/process/syscall.rs
  kernel/src/syscall/mod.rs
  user/apps/test_namespace/Cargo.toml
  user/apps/test_namespace/Makefile
  user/apps/test_namespace/makefile.toml
  user/apps/test_namespace/src/main.rs
  user/apps/test_overlayfs/.gitignore
  user/apps/test_overlayfs/Makefile
  user/apps/test_overlayfs/main.c
  user/dadk/config/test_namespace.dadk
  user/dadk/config/test_overlayfs.dadk
Labels: S-等待作者修改, T-doc, O-x86_64, O-riscv64, A-fs, ambiguous

#1023 ci: change rust src to crates-io-index while using GitHub workflow
  .github/workflows/makefile.yml
  tools/BUILD_CONTAINER_VERSION
  tools/docker-entrypoint.sh
Labels: S-等待审查

#1022 chore: Update NovaShell to cb835e03e4
  user/dadk/config/nova_shell-0.1.0.dadk
Labels: S-等待审查

#1027 fix: 删除在 #949 中意外添加的旧版ida
  kernel/src/libs/ida/src/lib.rs
Labels: Bug fix
