Repository DragonOS-Community/DragonOS, pull requests merged in 2024-03, with the labels that each got.

#574 Update Novashell version to 473d5c403c
  user/dadk/config/nova_shell-0.1.0.dadk
Labels: enhancement, Bug fix

#575 引入clippy，并根据clippy的提示，修改部分代码
  kernel/.clippy.toml
  kernel/crates/bitmap/src/lib.rs
  kernel/crates/crc/src/lib.rs
  kernel/crates/kdepends/src/lib.rs
  kernel/crates/klog_types/src/lib.rs
  kernel/crates/system_error/src/lib.rs
  kernel/crates/unified-init/src/lib.rs
  kernel/rust-toolchain.toml
  kernel/src/lib.rs
  kernel/src/libs/ida/src/lib.rs
  kernel/src/mm/page.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/process/fork.rs
  kernel/src/process/syscall.rs
  kernel/src/sched/cfs.rs
  kernel/src/syscall/misc.rs
  kernel/src/syscall/mod.rs
  kernel/src/time/clocksource.rs
  kernel/src/time/jiffies.rs
  kernel/src/time/mod.rs
  kernel/src/time/syscall.rs
  kernel/src/time/timeconv.rs
  kernel/src/time/timekeep.rs
  kernel/src/time/timer.rs
  kernel/src/virt/kvm/host_mem.rs
  kernel/src/virt/kvm/vm.rs
Labels: enhancement, Bug fix

#577 完善Tty的RawMode
  kernel/src/arch/x86_64/asm/entry.S
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/driver/tty/termios.rs
  kernel/src/driver/tty/tty_core.rs
  kernel/src/driver/tty/tty_device.rs
  kernel/src/driver/tty/tty_job_control.rs
  kernel/src/driver/tty/tty_ldisc/mod.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/driver/tty/virtual_terminal/mod.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/driver/video/fbdev/base/fbcon/framebuffer_console.rs
  kernel/src/driver/video/fbdev/base/mod.rs
  kernel/src/driver/video/fbdev/vesafb.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/ipc/signal.rs
  kernel/src/libs/printk.c
  kernel/src/libs/rwlock.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  kernel/src/process/syscall.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#582 Path-fix-clippy-240311new
  kernel/crates/bitmap/src/bitmap_core.rs
  kernel/crates/bitmap/src/traits.rs
  kernel/crates/unified-init/macros/src/lib.rs
  kernel/src/arch/x86_64/driver/apic/lapic_vector.rs
  kernel/src/arch/x86_64/interrupt/ipi.rs
  kernel/src/arch/x86_64/interrupt/trap.rs
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/base/device/dd.rs
  kernel/src/driver/base/device/device_number.rs
  kernel/src/driver/base/device/driver.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/disk/ahci/ahci_inode.rs
  kernel/src/driver/firmware/efi/tables.rs
  kernel/src/driver/net/e1000e/e1000e.rs
  kernel/src/driver/open_firmware/fdt.rs
  kernel/src/driver/tty/tty_driver.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/libs/elf.rs
  kernel/src/libs/futex/futex.rs
  kernel/src/libs/keyboard_parser.rs
  kernel/src/libs/lib_ui/textui.rs
  kernel/src/libs/lib_ui/textui_no_alloc.rs
  kernel/src/libs/rbtree.rs
  kernel/src/libs/vec_cursor.rs
Labels: enhancement, Bug fix

#583 修复get_random一个问题，添加Held配置文件
  kernel/src/syscall/misc.rs
  user/dadk/config/held-0.1.0.dadk
Labels: documentation, Bug fix

#591 暂时禁用load balance
  kernel/src/sched/cfs.rs
  kernel/src/sched/core.rs
  kernel/src/sched/rt.rs
Labels: Bug fix, Review effort [1-5]: 3, Other

#593 Update NovaShell version to c6454d3220
  user/dadk/config/nova_shell-0.1.0.dadk
Labels: enhancement, Review effort [1-5]: 3

#594 Patch fix clippy 202403121800
  kernel/crates/unified-init/macros/src/lib.rs
  kernel/src/arch/x86_64/kvm/vmx/vcpu.rs
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/timers/hpet/mod.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/driver/tty/virtual_terminal/console_map.rs
  kernel/src/driver/tty/virtual_terminal/mod.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/driver/video/fbdev/base/mod.rs
  kernel/src/filesystem/sysfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/ipc/signal.rs
  kernel/src/mm/allocator/buddy.rs
  kernel/src/mm/allocator/bump.rs
  kernel/src/mm/allocator/slab.rs
  kernel/src/mm/memblock.rs
  kernel/src/mm/page.rs
  kernel/src/mm/ucontext.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/process/exec.rs
  kernel/src/process/fork.rs
  kernel/src/sched/completion.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#595 heyicong 3-12
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/process/fork.rs
  kernel/src/process/kthread.rs
  kernel/src/process/mod.rs
  kernel/src/sched/cfs.rs
  kernel/src/sched/rt.rs
  kernel/src/sched/syscall.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/user_access.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#600 增加ChangeLog V0.1.9，更改about.c版本
  docs/community/ChangeLog/V0.1.x/V0.1.9.md
  docs/community/ChangeLog/index.rst
  docs/kernel/locking/locks.md
  user/apps/about/about.c
Labels: documentation, Review effort [1-5]: 2

#601 Patch fix clippy 202403132007
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/ramfs/mod.rs
  kernel/src/filesystem/sysfs/file.rs
  kernel/src/filesystem/vfs/core.rs
  kernel/src/filesystem/vfs/fcntl.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/init/init.rs
  kernel/src/ipc/signal.rs
  kernel/src/ipc/signal_types.rs
  kernel/src/ipc/syscall.rs
  kernel/src/mm/allocator/buddy.rs
  kernel/src/mm/allocator/bump.rs
  kernel/src/mm/allocator/kernel_allocator.rs
  kernel/src/mm/allocator/slab.rs
  kernel/src/mm/c_adapter.rs
  kernel/src/mm/early_ioremap.rs
  kernel/src/mm/memblock.rs
  kernel/src/mm/mmio_buddy.rs
  kernel/src/mm/mod.rs
  kernel/src/mm/no_init.rs
  kernel/src/mm/page.rs
  kernel/src/mm/syscall.rs
  kernel/src/mm/ucontext.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/net/event_poll/syscall.rs
  kernel/src/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/syscall.rs
  kernel/src/process/exit.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  kernel/src/sched/completion.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 4

#602 Patch fix clippy 0314-morning
  kernel/src/arch/x86_64/driver/apic/apic_timer.rs
  kernel/src/arch/x86_64/driver/apic/ioapic.rs
  kernel/src/arch/x86_64/driver/apic/x2apic.rs
  kernel/src/arch/x86_64/driver/apic/xapic.rs
  kernel/src/arch/x86_64/driver/hpet.rs
  kernel/src/arch/x86_64/driver/tsc.rs
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/driver/base/kset.rs
  kernel/src/driver/base/map/mod.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/disk/ahci/ahcidisk.rs
Labels: enhancement, Review effort [1-5]: 3, bug_fix, tests

#603 Patch fix clippy
  kernel/src/driver/disk/ahci/ahcidisk.rs
  kernel/src/mm/percpu.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/net/event_poll/syscall.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/sockets.rs
  kernel/src/process/exec.rs
  kernel/src/process/kthread.rs
Labels: enhancement, Bug fix

#607 Patch fix clippy 0315afternoon
  kernel/src/filesystem/fat/entry.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/sysfs/mod.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/ipc/pipe.rs
  kernel/src/ipc/signal.rs
  kernel/src/ipc/signal_types.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#608 添加triagebot文件
  triagebot.toml
Labels: enhancement, Review effort [1-5]: 3

#609 Patch fix clippy 0315evening
  kernel/src/exception/irqdomain.rs
  kernel/src/exception/manage.rs
  kernel/src/filesystem/fat/bpb.rs
  kernel/src/filesystem/fat/entry.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#613 0316afternoon
  kernel/src/driver/virtio/irq.rs
  kernel/src/driver/virtio/virtio_impl.rs
  kernel/src/exception/handle.rs
  kernel/src/exception/irqchip.rs
  kernel/src/exception/irqdata.rs
  kernel/src/exception/irqdesc.rs
  kernel/src/exception/irqdomain.rs
  kernel/src/exception/manage.rs
  kernel/src/exception/sysfs.rs
  kernel/src/filesystem/fat/entry.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/kernfs/mod.rs
  kernel/src/filesystem/procfs/syscall.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/init/mod.rs
  kernel/src/ipc/pipe.rs
  kernel/src/ipc/signal_types.rs
  kernel/src/net/syscall.rs
Labels: documentation, enhancement, Bug fix, Review effort [1-5]: 3

#616 更新triagebot配置
  triagebot.toml
Labels: enhancement, Review effort [1-5]: 3, S-等待审查, A-meta

#617 Patch fix clippy
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/exception/irqdata.rs
  kernel/src/filesystem/fat/entry.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/mbr.rs
  kernel/src/ipc/pipe.rs
  kernel/src/ipc/signal.rs
  kernel/src/ipc/signal_types.rs
  kernel/src/ipc/syscall.rs
  kernel/src/mm/allocator/buddy.rs
  kernel/src/mm/percpu.rs
Labels: documentation, enhancement, Bug fix, Review effort [1-5]: 3

#578 实现了sys_rename
  kernel/src/filesystem/fat/entry.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/kernfs/mod.rs
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/ramfs/mod.rs
  kernel/src/filesystem/vfs/core.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
Labels: enhancement, Bug fix, S-等待作者修改, A-fs

#618 patch-fix-clippy-0317evening
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/base/class.rs
  kernel/src/driver/base/device/bus.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/driver/video/fbdev/base/fbcon/framebuffer_console.rs
  kernel/src/driver/video/fbdev/base/mod.rs
  kernel/src/libs/futex/futex.rs
  kernel/src/libs/keyboard_parser.rs
  kernel/src/libs/vec_cursor.rs
  kernel/src/libs/wait_queue.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 4, S-等待审查

#620 Patch fix clippy 35 warnings and errors
  kernel/src/arch/x86_64/driver/apic/ioapic.rs
  kernel/src/arch/x86_64/driver/apic/mod.rs
  kernel/src/arch/x86_64/driver/apic/x2apic.rs
  kernel/src/arch/x86_64/driver/hpet.rs
  kernel/src/arch/x86_64/init/mod.rs
  kernel/src/arch/x86_64/interrupt/handle.rs
  kernel/src/arch/x86_64/interrupt/ipi.rs
  kernel/src/arch/x86_64/interrupt/mod.rs
  kernel/src/arch/x86_64/interrupt/trap.rs
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/arch/x86_64/kvm/mod.rs
  kernel/src/arch/x86_64/kvm/vmx/mmu.rs
  kernel/src/arch/x86_64/kvm/vmx/vcpu.rs
  kernel/src/arch/x86_64/kvm/vmx/vmcs.rs
  kernel/src/arch/x86_64/kvm/vmx/vmexit.rs
  kernel/src/arch/x86_64/mm/bump.rs
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/syscall/mod.rs
Labels: enhancement, Bug fix, T-virtulization, T-driver

#622 Patch fix clippy 0318night
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/driver/video/fbdev/vesafb.rs
  kernel/src/driver/video/mod.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 4, S-等待作者修改, T-virtulization, T-driver

#615 fix: mkdir输出错误信息; feat: 实现get_pathname
  kernel/src/filesystem/vfs/core.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/user_access.rs
Labels: enhancement, Bug fix, Review effort [1-5]: 3, S-等待审查, A-fs

#614 实现uname系统调用
  kernel/Cargo.toml
  kernel/src/process/syscall.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/syscall_num.h
Labels: enhancement, Bug fix, Review effort [1-5]: 3, S-等待作者修改

#624 添加core utils到系统
  user/Makefile
  user/dadk/config/core_utils-9.4.0.dadk
  user/dadk/config/musl_1_2_4.dadk
Labels: S-等待审查

#626 0320早上
  kernel/crates/bitmap/src/traits.rs
  kernel/src/arch/x86_64/driver/apic/mod.rs
  kernel/src/driver/net/e1000e/e1000e.rs
  kernel/src/driver/net/e1000e/e1000e_driver.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/pci/pci.rs
  kernel/src/driver/serial/serial8250/mod.rs
  kernel/src/driver/serial/serial8250/serial8250_pio.rs
  kernel/src/driver/timers/rtc/rtc.rs
  kernel/src/driver/tty/termios.rs
  kernel/src/driver/tty/tty_core.rs
  kernel/src/driver/tty/tty_device.rs
  kernel/src/driver/tty/tty_driver.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/driver/video/fbdev/vesafb.rs
  kernel/src/driver/video/mod.rs
  kernel/src/exception/handle.rs
  kernel/src/filesystem/devfs/zero_dev.rs
  kernel/src/filesystem/fat/entry.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/ipc/pipe.rs
  kernel/src/process/mod.rs
Labels: S-等待审查, A-fs, T-driver

#561 添加mount系统调用
  .gitignore
  .vscode/settings.json
  kernel/src/filesystem/devfs/mod.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/kernfs/mod.rs
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/ramfs/mod.rs
  kernel/src/filesystem/vfs/core.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/syscall_num.h
  user/apps/test-mount/.gitignore
  user/apps/test-mount/Cargo.toml
  user/apps/test-mount/Makefile
  user/apps/test-mount/README.md
  user/apps/test-mount/src/main.rs
  user/dadk/config/test_mount_1_0_0.dadk
Labels: S-等待审查, A-fs

#627 fix clippy
  kernel/src/arch/x86_64/interrupt/handle.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/input/ps2_mouse/ps_mouse_device.rs
  kernel/src/driver/net/dma.rs
  kernel/src/driver/net/e1000e/e1000e.rs
  kernel/src/driver/net/e1000e/e1000e_driver.rs
  kernel/src/driver/net/e1000e/mod.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/pci/mod.rs
  kernel/src/driver/pci/pci.rs
  kernel/src/driver/serial/serial8250/serial8250_pio.rs
  kernel/src/driver/timers/rtc/mod.rs
  kernel/src/driver/tty/console.rs
  kernel/src/driver/tty/termios.rs
  kernel/src/driver/tty/tty_driver.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/driver/tty/virtual_terminal/mod.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/driver/video/fbdev/base/fbcon/framebuffer_console.rs
  kernel/src/driver/video/fbdev/base/fbcon/mod.rs
  kernel/src/driver/video/fbdev/base/mod.rs
  kernel/src/driver/virtio/mod.rs
  kernel/src/exception/handle.rs
  kernel/src/exception/irqchip.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/ipc/pipe.rs
  kernel/src/ipc/signal.rs
  kernel/src/lib.rs
  kernel/src/mm/mod.rs
  kernel/src/mm/syscall.rs
  kernel/src/mm/ucontext.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/sockets.rs
  kernel/src/net/syscall.rs
  kernel/src/process/exec.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  kernel/src/process/stdio.rs
  kernel/src/process/utils.rs
Labels: S-等待审查, T-driver

#628 patch-fix-clippy-0320afternoon
  kernel/src/driver/base/device/bus.rs
  kernel/src/driver/base/device/dd.rs
  kernel/src/driver/disk/ahci/hba.rs
  kernel/src/driver/firmware/efi/init.rs
  kernel/src/driver/firmware/efi/tables.rs
  kernel/src/libs/futex/futex.rs
  kernel/src/libs/lib_ui/textui.rs
  kernel/src/libs/mutex.rs
  kernel/src/libs/printk.rs
  kernel/src/libs/rbtree.rs
Labels: T-driver

#629 Patch fix clippy
  kernel/src/arch/x86_64/cpu.rs
  kernel/src/arch/x86_64/driver/apic/ioapic.rs
  kernel/src/arch/x86_64/driver/apic/mod.rs
  kernel/src/arch/x86_64/driver/apic/xapic.rs
  kernel/src/arch/x86_64/interrupt/ipi.rs
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/driver/base/device/bus.rs
  kernel/src/driver/firmware/efi/fdt.rs
  kernel/src/driver/firmware/efi/init.rs
  kernel/src/driver/firmware/efi/tables.rs
  kernel/src/lib.rs
  kernel/src/libs/elf.rs
  kernel/src/libs/keyboard_parser.rs
  kernel/src/libs/lib_ui/screen_manager.rs
  kernel/src/libs/lib_ui/textui.rs
  kernel/src/libs/rbtree.rs
  kernel/src/libs/rwlock.rs
  kernel/src/libs/spinlock.rs
  kernel/src/libs/vec_cursor.rs
Labels: T-driver

#630 patch-fix-clippy-0321morning
  kernel/src/arch/x86_64/kvm/mod.rs
  kernel/src/arch/x86_64/kvm/vmx/vcpu.rs
  kernel/src/arch/x86_64/process/mod.rs
  kernel/src/arch/x86_64/process/table.rs
  kernel/src/driver/base/block/block_device.rs
  kernel/src/driver/base/device/bus.rs
  kernel/src/driver/base/device/dd.rs
  kernel/src/driver/base/device/driver.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/libs/elf.rs
  kernel/src/libs/keyboard_parser.rs
Labels: S-等待审查, T-virtulization, T-driver

#631 patch-fix-clippy-0321afternoon
  kernel/src/driver/base/device/bus.rs
  kernel/src/driver/base/device/driver.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/map/mod.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/disk/ahci/ahcidisk.rs
  kernel/src/driver/disk/ahci/hba.rs
  kernel/src/driver/disk/ahci/mod.rs
  kernel/src/driver/firmware/efi/fdt.rs
  kernel/src/libs/elf.rs
  kernel/src/libs/notifier.rs
Labels: S-等待审查, T-driver

#633 重写SMP模块
  kernel/src/Makefile
  kernel/src/arch/riscv64/smp/mod.rs
  kernel/src/arch/riscv64/time.rs
  kernel/src/arch/x86_64/asm/apu_boot.S
  kernel/src/arch/x86_64/c_adapter.rs
  kernel/src/arch/x86_64/cpu.rs
  kernel/src/arch/x86_64/init/main.c
  kernel/src/arch/x86_64/init/mod.rs
  kernel/src/arch/x86_64/interrupt/c_adapter.rs
  kernel/src/arch/x86_64/interrupt/ipi.rs
  kernel/src/arch/x86_64/interrupt/mod.rs
  kernel/src/arch/x86_64/mm/c_adapter.rs
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/arch/x86_64/mod.rs
  kernel/src/arch/x86_64/smp/mod.rs
  kernel/src/arch/x86_64/time.rs
  kernel/src/common/cpu.h
  kernel/src/driver/keyboard/ps2_keyboard.rs
  kernel/src/driver/tty/virtual_terminal/mod.rs
  kernel/src/exception/mod.rs
  kernel/src/include/bindings/wrapper.h
  kernel/src/init/init.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/libs/cpu.c
  kernel/src/libs/cpumask.rs
  kernel/src/libs/wait_queue.rs
  kernel/src/mm/mod.rs
  kernel/src/mm/percpu.rs
  kernel/src/process/idle.rs
  kernel/src/process/mod.rs
  kernel/src/process/process.h
  kernel/src/sched/cfs.rs
  kernel/src/sched/rt.rs
  kernel/src/smp/Makefile
  kernel/src/smp/c_adapter.rs
  kernel/src/smp/cpu/c_adapter.rs
  kernel/src/smp/cpu/mod.rs
  kernel/src/smp/init.rs
  kernel/src/smp/mod.rs
  kernel/src/smp/smp.c
  kernel/src/smp/smp.h
  kernel/src/time/mod.rs
  kernel/src/time/sleep.rs
  kernel/src/time/timer.rs
Labels: S-等待审查, T-driver

#632 Statx
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
  user/apps/test_statx/.gitignore
  user/apps/test_statx/Cargo.toml
  user/apps/test_statx/Makefile
  user/apps/test_statx/src/main.rs
  user/dadk/config/test_statx_0_1_0.dadk
Labels: S-等待作者修改, A-fs

#636 riscv64: 添加flush tlb的ipi
  kernel/src/arch/riscv64/cpu.rs
  kernel/src/arch/riscv64/interrupt/ipi.rs
  kernel/src/arch/riscv64/mm/mod.rs
  kernel/src/mm/percpu.rs
  kernel/src/syscall/mod.rs
  triagebot.toml
Labels: S-等待审查, A-meta

#635 patch-fix-clippy-240321evening
  kernel/src/arch/x86_64/interrupt/ipi.rs
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/arch/x86_64/kvm/vmx/mmu.rs
  kernel/src/arch/x86_64/pci/mod.rs
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/driver/base/device/dd.rs
  kernel/src/driver/base/device/driver.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/kobject.rs
  kernel/src/driver/disk/ahci/mod.rs
  kernel/src/driver/firmware/efi/fdt.rs
  kernel/src/include/bindings/mod.rs
  kernel/src/ipc/pipe.rs
  kernel/src/libs/align.rs
  kernel/src/libs/elf.rs
  kernel/src/libs/futex/mod.rs
  kernel/src/libs/lib_ui/textui.rs
  kernel/src/libs/lock_free_flags.rs
  kernel/src/libs/notifier.rs
  kernel/src/libs/rbtree.rs
  kernel/src/libs/semaphore.rs
  kernel/src/libs/wait_queue.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/process/mod.rs
  kernel/src/sched/completion.rs
Labels: S-等待审查, T-driver

#611 实现SYS_LINK和SYS_LINKAT
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/syscall_num.h
Labels: enhancement, Bug fix, S-等待作者修改, A-fs

#649 添加clippy检测的自动化工作流
  kernel/Makefile
  kernel/src/filesystem/vfs/syscall.rs
Labels: S-等待审查, A-fs

#651 只对x86_64进行clippy check
  kernel/Makefile
Labels: S-等待审查

#576 Patch socketpair
  kernel/src/filesystem/fat/entry.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/inet.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/unix.rs
  kernel/src/net/syscall.rs
  user/apps/test_socket/.gitignore
  user/apps/test_socket/Cargo.toml
  user/apps/test_socket/Makefile
  user/apps/test_socket/src/main.rs
  user/apps/test_socket/src/test_unix_stream.rs
  user/apps/test_socket/src/test_unix_stream_pair.rs
  user/dadk/config/test_socket-0.1.0.dadk
Labels: enhancement, Bug fix, Review effort [1-5]: 3, S-等待审查, A-fs

#654 riscv: 进程管理初始化
  kernel/src/arch/riscv64/init/mod.rs
  kernel/src/arch/riscv64/process/mod.rs
  kernel/src/arch/riscv64/smp/mod.rs
  kernel/src/arch/riscv64/syscall/mod.rs
  kernel/src/arch/x86_64/process/mod.rs
  kernel/src/process/idle.rs
  kernel/src/process/mod.rs
Labels: S-等待审查, O-x86_64, O-riscv64

#664 修复clock_gettime返回类型错误，修复小时间间隔duration返回0问题
  kernel/src/time/syscall.rs
  kernel/src/time/timekeeping.rs
  user/apps/test-mount/src/main.rs
Labels: S-等待审查, O-x86_64, T-driver

#652 移植dns查询工具dog的--tcp功能
  env.mk
  kernel/Makefile
  kernel/env.mk
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  user/Makefile
  user/dadk/config/dog_0_1_0.dadk
  user/sysconfig/etc/reach/system/shell.service
  user/sysconfig/etc/resolv.conf
Labels: S-等待审查, T-driver

#665 修改bug report模版label
  .github/ISSUE_TEMPLATE/bug_report.md
  triagebot.toml
Labels: S-等待审查, A-meta

#666 把Device trait的set_class改为设置Weak指针，以避免循环引用问题。
  kernel/src/driver/base/cpu.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/base/subsys.rs
  kernel/src/driver/disk/ahci/ahcidisk.rs
  kernel/src/driver/input/ps2_mouse/ps_mouse_device.rs
  kernel/src/driver/input/serio/i8042/i8042_device.rs
  kernel/src/driver/input/serio/i8042/i8042_ports.rs
  kernel/src/driver/serial/serial8250/mod.rs
  kernel/src/driver/tty/tty_device.rs
  kernel/src/driver/video/fbdev/base/fbcon/mod.rs
  kernel/src/driver/video/fbdev/base/fbmem.rs
  kernel/src/driver/video/fbdev/vesafb.rs
Labels: S-等待审查, A-driver, T-driver

#668 修复tty设备显示在/sys目录下的bug
  kernel/src/driver/tty/mod.rs
  kernel/src/driver/tty/sysfs.rs
  kernel/src/driver/tty/tty_device.rs
Labels: S-等待审查, T-driver

#667 Statfs dev
  kernel/src/filesystem/devfs/mod.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/filesystem/kernfs/mod.rs
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/ramfs/mod.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
  user/apps/test_fstatfs/.gitignore
  user/apps/test_fstatfs/Makefile
  user/apps/test_fstatfs/main.c
  user/apps/test_statfs/.gitignore
  user/apps/test_statfs/Makefile
  user/apps/test_statfs/main.c
  user/dadk/config/test_fstatfs_0_1_0.dadk
  user/dadk/config/test_statfs_0_1_0.dadk
Labels: S-等待审查, A-fs

#674 实现了rtc的抽象，并且把x86的cmos rtc接入到设备驱动模型
  kernel/Cargo.toml
  kernel/crates/driver_base_macros/Cargo.toml
  kernel/crates/driver_base_macros/src/lib.rs
  kernel/src/arch/x86_64/driver/mod.rs
  kernel/src/arch/x86_64/driver/rtc.rs
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/driver/base/device/dd.rs
  kernel/src/driver/base/device/driver.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/kobject.rs
  kernel/src/driver/base/platform/platform_device.rs
  kernel/src/driver/input/serio/i8042/i8042_device.rs
  kernel/src/driver/mod.rs
  kernel/src/driver/rtc/class.rs
  kernel/src/driver/rtc/interface.rs
  kernel/src/driver/rtc/mod.rs
  kernel/src/driver/rtc/rtc_cmos.rs
  kernel/src/driver/rtc/sysfs.rs
  kernel/src/driver/rtc/utils.rs
  kernel/src/driver/serial/serial8250/mod.rs
  kernel/src/driver/timers/mod.rs
  kernel/src/driver/timers/rtc/mod.rs
  kernel/src/driver/timers/rtc/rtc.rs
  kernel/src/driver/tty/virtual_terminal/virtual_console.rs
  kernel/src/driver/video/fbdev/vesafb.rs
  kernel/src/time/mod.rs
  kernel/src/time/timekeep.rs
  kernel/src/time/timekeeping.rs
Labels: S-等待审查, O-x86_64, T-driver

#676 fix udp bind
  kernel/src/net/socket/inet.rs
Labels: S-等待审查

#673 修复了ramfs中move_to的bug
  kernel/src/filesystem/ramfs/mod.rs
Labels: S-等待作者修改, A-fs

#670 实现页面反向映射
  kernel/src/driver/net/dma.rs
  kernel/src/driver/virtio/virtio_impl.rs
  kernel/src/mm/allocator/page_frame.rs
  kernel/src/mm/init.rs
  kernel/src/mm/page.rs
  kernel/src/mm/ucontext.rs
Labels: S-等待审查, A-mm, T-driver

#677 Modify get_random()
  kernel/src/syscall/misc.rs
Labels: S-等待作者修改

#678 riscv64: switch process
  kernel/Cargo.toml
  kernel/src/arch/riscv64/cpu.rs
  kernel/src/arch/riscv64/interrupt/mod.rs
  kernel/src/arch/riscv64/process/mod.rs
  kernel/src/syscall/mod.rs
Labels: S-等待审查, O-riscv64
