Repository DragonOS-Community/DragonOS, pull requests merged in 2024-08, with the labels that each got.

#846 feat(cred): 初步实现Cred
  kernel/src/filesystem/vfs/file.rs
  kernel/src/process/cred.rs
  kernel/src/process/mod.rs
  kernel/src/process/syscall.rs
  kernel/src/syscall/mod.rs
  user/apps/test_cred/.gitignore
  user/apps/test_cred/Makefile
  user/apps/test_cred/main.c
  user/dadk/config/test_cred-0.1.0.dadk
  user/sysconfig/etc/group
  user/sysconfig/etc/gshadow
  user/sysconfig/etc/passwd
  user/sysconfig/etc/shadow
Labels: enhancement, S-等待审查, A-fs

#878 Feature/network-syscall
  kernel/Cargo.toml
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/process/cred.rs
  kernel/src/process/mod.rs
  kernel/src/process/syscall.rs
  kernel/src/sched/mod.rs
  kernel/src/syscall/mod.rs
  user/apps/test_cred/.gitignore
  user/apps/test_cred/Makefile
  user/apps/test_cred/main.c
  user/apps/test_lo/src/main.rs
  user/dadk/config/test_cred-0.1.0.dadk
  user/sysconfig/etc/group
  user/sysconfig/etc/gshadow
  user/sysconfig/etc/passwd
  user/sysconfig/etc/shadow
Labels: ambiguous

#877 fix: 修复键盘码解析器没能正确处理类似ctrl C的控制字符的问题
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/libs/keyboard_parser.rs
Labels: Bug fix, A-driver

#880 [feat](namespace) add pid_namespace
  kernel/src/cgroup/cgroup.rs
  kernel/src/cgroup/mod.rs
  kernel/src/lib.rs
  kernel/src/namespace/mod.rs
  kernel/src/namespace/namespace.rs
  kernel/src/namespace/pid_namespace.rs
  kernel/src/namespace/ucount.rs
  kernel/src/namespace/user_namespace.rs
Labels: ambiguous

#879 user(app): 初步实现rust ping 用户程序
  kernel/src/driver/net/loopback.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/net/net_core.rs
  tools/run-qemu.sh
  user/apps/ping/.gitignore
  user/apps/ping/Cargo.toml
  user/apps/ping/Makefile
  user/apps/ping/README.md
  user/apps/ping/src/args.rs
  user/apps/ping/src/config.rs
  user/apps/ping/src/error.rs
  user/apps/ping/src/main.rs
  user/apps/ping/src/ping.rs
  user/apps/test_lo/src/main.rs
  user/dadk/config/ping_0_1_0.dadk
Labels: A-driver, A-network

#892 fix: 修复do_unlink_at函数中的路径错误
  kernel/src/filesystem/vfs/core.rs
Labels: Bug fix, A-fs

#883 feat(bpf): add rbpf crate
  .github/workflows/makefile.yml
  kernel/crates/rbpf/.appveyor.yml
  kernel/crates/rbpf/.gitignore
  kernel/crates/rbpf/Cargo.toml
  kernel/crates/rbpf/LICENSE-APACHE
  kernel/crates/rbpf/LICENSE-MIT
  kernel/crates/rbpf/README.md
  kernel/crates/rbpf/clippy.toml
  kernel/crates/rbpf/examples/disassemble.rs
  kernel/crates/rbpf/examples/load_elf.rs
  kernel/crates/rbpf/examples/load_elf__block_a_port.c
  kernel/crates/rbpf/examples/load_elf__block_a_port.elf
  kernel/crates/rbpf/examples/rbpf_plugin.rs
  kernel/crates/rbpf/examples/to_json.rs
  kernel/crates/rbpf/examples/uptime.rs
  kernel/crates/rbpf/misc/rbpf.ico
  kernel/crates/rbpf/misc/rbpf.png
  kernel/crates/rbpf/misc/rbpf.svg
  kernel/crates/rbpf/misc/rbpf_256.png
  kernel/crates/rbpf/misc/rbpf_256_border.png
  kernel/crates/rbpf/misc/rbpf_bg.png
  kernel/crates/rbpf/mk/appveyor.bat
  kernel/crates/rbpf/rustfmt.toml
  kernel/crates/rbpf/src/asm_parser.rs
  kernel/crates/rbpf/src/assembler.rs
  kernel/crates/rbpf/src/cranelift.rs
  kernel/crates/rbpf/src/disassembler.rs
  kernel/crates/rbpf/src/ebpf.rs
  kernel/crates/rbpf/src/helpers.rs
  kernel/crates/rbpf/src/insn_builder.rs
  kernel/crates/rbpf/src/interpreter.rs
  kernel/crates/rbpf/src/jit.rs
  kernel/crates/rbpf/src/lib.rs
  kernel/crates/rbpf/src/no_std_error.rs
  kernel/crates/rbpf/src/stack.rs
  kernel/crates/rbpf/src/verifier.rs
  kernel/crates/rbpf/tests/assembler.rs
  kernel/crates/rbpf/tests/common.rs
  kernel/crates/rbpf/tests/cranelift.rs
  kernel/crates/rbpf/tests/disassembler.rs
  kernel/crates/rbpf/tests/misc.rs
  kernel/crates/rbpf/tests/ubpf_jit_x86_64.rs
  kernel/crates/rbpf/tests/ubpf_verifier.rs
  kernel/crates/rbpf/tests/ubpf_vm.rs
  kernel/src/filesystem/vfs/core.rs
Labels: enhancement, A-fs

#893 fix: socket shutdown wrong implement
  kernel/src/net/syscall.rs
Labels: Bug fix, A-network

#895 重构
  .github/workflows/makefile.yml
  kernel/src/driver/net/e1000e/e1000e_driver.rs
  kernel/src/driver/net/irq_handle.rs
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/filesystem/vfs/core.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/libs/keyboard_parser.rs
  kernel/src/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/common/mod.rs
  kernel/src/net/socket/common/poll_unit.rs
  kernel/src/net/socket/common/shutdown.rs
  kernel/src/net/socket/define.rs
  kernel/src/net/socket/inet.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/common/port.rs
  kernel/src/net/socket/inet/datagram/inner.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/ip_def.rs
  kernel/src/net/socket/inet/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inet/syscall.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/old/handle.rs
  kernel/src/net/socket/old/icmp.rs
  kernel/src/net/socket/old/inode/mod.rs
  kernel/src/net/socket/old/old.rs
  kernel/src/net/socket/old/poll_method.rs
  kernel/src/net/socket/old/raw/mod.rs
  kernel/src/net/socket/tcp_def.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/syscall.rs
  kernel/src/process/mod.rs
  user/apps/test_lo/src/main.rs
Labels: In-progress, A-driver, A-fs, A-network

#852 feat(kprobe): Add basic kprobe support for x86_64
  kernel/Cargo.toml
  kernel/crates/kprobe/Cargo.toml
  kernel/crates/kprobe/src/arch/loongarch64/mod.rs
  kernel/crates/kprobe/src/arch/mod.rs
  kernel/crates/kprobe/src/arch/rv64/mod.rs
  kernel/crates/kprobe/src/arch/x86/mod.rs
  kernel/crates/kprobe/src/lib.rs
  kernel/src/arch/riscv64/interrupt/handle.rs
  kernel/src/arch/riscv64/interrupt/mod.rs
  kernel/src/arch/riscv64/kprobe.rs
  kernel/src/arch/riscv64/mod.rs
  kernel/src/arch/x86_64/interrupt/mod.rs
  kernel/src/arch/x86_64/interrupt/trap.rs
  kernel/src/arch/x86_64/kprobe.rs
  kernel/src/arch/x86_64/mod.rs
  kernel/src/debug/kprobe/args.rs
  kernel/src/debug/kprobe/mod.rs
  kernel/src/debug/kprobe/test.rs
  kernel/src/debug/mod.rs
  kernel/src/debug/traceback/traceback.c
  kernel/src/debug/traceback/traceback.h
  kernel/src/exception/debug.rs
  kernel/src/exception/ebreak.rs
  kernel/src/exception/mod.rs
  kernel/src/init/init.rs
Labels: enhancement, O-x86_64, O-riscv64

#894 feat: 增加tokio异步运行时支持
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/ipc/pipe.rs
  user/apps/test_tokio/.gitignore
  user/apps/test_tokio/Cargo.toml
  user/apps/test_tokio/Makefile
  user/apps/test_tokio/src/main.rs
  user/dadk/config/test_tokio-0.1.0.dadk
Labels: enhancement, A-fs

#897 fix: af_netlink problems in the new branch reported by RA
  .vscode/settings.json
  kernel/src/driver/acpi/sysfs.rs
  kernel/src/driver/base/device/dd.rs
  kernel/src/driver/base/device/driver.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/base/kobject.rs
  kernel/src/driver/base/kset.rs
  kernel/src/driver/base/mod.rs
  kernel/src/driver/base/uevent/kobject_uevent.rs
  kernel/src/driver/base/uevent/mod.rs
  kernel/src/driver/net/mod.rs
  kernel/src/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/inet.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/netlink/af_netlink.rs
  kernel/src/net/socket/netlink/callback.rs
  kernel/src/net/socket/netlink/endpoint.rs
  kernel/src/net/socket/netlink/mod.rs
  kernel/src/net/socket/netlink/netlink.rs
  kernel/src/net/socket/netlink/netlink_diag.rs
  kernel/src/net/socket/netlink/netlink_proto.rs
  kernel/src/net/socket/netlink/netlink_socket.rs
  kernel/src/net/socket/netlink/skbuff.rs
  kernel/src/net/socket/netlink/sock.rs
  kernel/src/net/socket/unix/mod.rs
  kernel/src/net/syscall.rs
  kernel/src/process/mod.rs
  kernel/src/syscall/mod.rs
  user/apps/test-uevent/.cargo/config.toml
  user/apps/test-uevent/.gitignore
  user/apps/test-uevent/Cargo.toml
  user/apps/test-uevent/Makefile
  user/apps/test-uevent/README.md
  user/apps/test-uevent/src/main.rs
  user/apps/test_lo/src/main.rs
  user/dadk/config/test_uevent_0_1_0.dadk
Labels: Bug fix, A-network

#899 disable font size setting
  .vscode/settings.json
Labels: ambiguous

#889 fix: pipe 读取/写入阻塞时,无法kill进程的问题
  kernel/Cargo.toml
  kernel/crates/wait_queue_macros/Cargo.toml
  kernel/crates/wait_queue_macros/src/lib.rs
  kernel/src/arch/x86_64/interrupt/mod.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/ipc/pipe.rs
  kernel/src/ipc/signal.rs
  kernel/src/ipc/signal_types.rs
  kernel/src/lib.rs
  kernel/src/libs/wait_queue.rs
  kernel/src/mm/page.rs
  kernel/src/process/kthread.rs
  kernel/src/process/mod.rs
  kernel/src/sched/fair.rs
Labels: Bug fix, A-sched, O-x86_64, A-fs, A-IPC

#905 feat: define socket trait, move unused definitions into socket/define
  kernel/src/net/mod.rs
  kernel/src/net/socket/base.rs
  kernel/src/net/socket/define.rs
  kernel/src/net/socket/define/ipproto.rs
  kernel/src/net/socket/define/mod.rs
  kernel/src/net/socket/define/msg_flag.rs
  kernel/src/net/socket/define/option.rs
  kernel/src/net/socket/define/option_level.rs
  kernel/src/net/socket/define/tmp.rs
  kernel/src/net/socket/endpoint.rs
  kernel/src/net/socket/inet/mod.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/inet/syscall.rs
  kernel/src/net/socket/inode.rs
  kernel/src/net/socket/mod.rs
  kernel/src/net/socket/utils.rs
  kernel/src/net/syscall.rs
  kernel/src/net/syscall_util.rs
  kernel/src/syscall/mod.rs
Labels: enhancement

#904 fix: 修复存在多个virtio设备时，中断号冲突的问题
  kernel/src/driver/pci/pci_irq.rs
  kernel/src/init/initial_kthread.rs
Labels: Bug fix, A-driver, A-irq

#888 feat(namespace): add mnt_namespace
  kernel/src/cgroup/cgroup.rs
  kernel/src/cgroup/mem_cgroup.rs
  kernel/src/cgroup/mod.rs
  kernel/src/libs/ida/src/lib.rs
  kernel/src/namespace/mnt_namespace.rs
  kernel/src/namespace/mod.rs
  kernel/src/namespace/namespace.rs
  kernel/src/namespace/pid_namespace.rs
  kernel/src/namespace/ucount.rs
  kernel/src/namespace/user_namespace.rs
  kernel/src/process/mod.rs
Labels: enhancement
