Repository DragonOS-Community/DragonOS, pull requests merged in 2025-05, with the labels that each got.

#1152 fix(boot): won't fail to boot when kvm not available
  kernel/src/arch/x86_64/vm/vmx/mod.rs
  kernel/src/init/init.rs
Labels: Bug fix

#1154 fix: 修复无法执行当前目录下程序的bug
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/namespaces/mnt_namespace.rs
  kernel/src/namespaces/mod.rs
  kernel/src/namespaces/namespace.rs
  kernel/src/process/exec.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  tools/run-qemu.sh
Labels: Bug fix

#1153 feat: 实现并测试 newfstatat 系统调用
  kernel/src/arch/loongarch64/filesystem/mod.rs
  kernel/src/arch/loongarch64/filesystem/stat.rs
  kernel/src/arch/loongarch64/mod.rs
  kernel/src/arch/riscv64/filesystem/mod.rs
  kernel/src/arch/riscv64/filesystem/stat.rs
  kernel/src/arch/riscv64/mod.rs
  kernel/src/arch/x86_64/filesystem/mod.rs
  kernel/src/arch/x86_64/filesystem/stat.rs
  kernel/src/arch/x86_64/mod.rs
  kernel/src/driver/base/device/device_number.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/stat.rs
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
  user/apps/test_newfstatat/.gitignore
  user/apps/test_newfstatat/Makefile
  user/apps/test_newfstatat/main.c
  user/dadk/config/test_newfstatat-0.1.0.toml
Labels: enhancement

#1135 fix bugs in poll and epoll
  kernel/src/driver/tty/tty_port.rs
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/poll.rs
  kernel/src/ipc/pipe.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/perf/mod.rs
  user/apps/test_epoll/main.c
Labels: ambiguous

#1161 Feat：修改busybox编译选项，启用busybox作为初始引导程序以及shell程序
  tools/run-qemu.sh
  user/apps/busybox/Makefile
  user/sysconfig/etc/init.d/rcS
Labels: ambiguous

#1162 fix: 为ctrl+C设置trap，防止shell进程意外退出
  user/sysconfig/etc/profile
Labels: Bug fix

#1164 feat(syscall): 添加syscall table的实现
  docs/conf.py
  docs/index.rst
  docs/kernel/filesystem/overview.md
  docs/kernel/syscall/index.rst
  docs/kernel/syscall/syscall_table.rst
  docs/requirements.txt
  docs/syscall_api/intro.md
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/crates/syscall_table_macros/Cargo.toml
  kernel/crates/syscall_table_macros/src/lib.rs
  kernel/src/arch/loongarch64/link.ld
  kernel/src/arch/riscv64/link.ld
  kernel/src/arch/x86_64/link.lds
  kernel/src/filesystem/mbr.rs
  kernel/src/filesystem/vfs/iov.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/syscall/mod.rs
  kernel/src/filesystem/vfs/syscall/sys_read.rs
  kernel/src/filesystem/vfs/syscall/sys_readv.rs
  kernel/src/filesystem/vfs/syscall/sys_write.rs
  kernel/src/filesystem/vfs/syscall/sys_writev.rs
  kernel/src/init/init.rs
  kernel/src/net/syscall.rs
  kernel/src/syscall/mod.rs
  kernel/src/syscall/table.rs
  user/apps/riscv_init/Makefile
  user/apps/riscv_init/main.c
  user/dadk/config/riscv_init-0.1.0.toml
Labels: enhancement

#1170 docs: 更新README文件并添加README_CN.md和SUPPORTERS.md
  README.md
  README_CN.md
  README_EN.md
  SUPPORTERS.md
Labels: documentation

#1172 fix: 修复部分函数的爆栈问题
  kernel/.clippy.toml
  kernel/src/arch/x86_64/driver/tsc.rs
  kernel/src/arch/x86_64/interrupt/entry.rs
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/driver/disk/ahci/mod.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/filesystem/fat/fs.rs
  kernel/src/lib.rs
  kernel/src/mm/fault.rs
Labels: Bug fix
