Repository DragonOS-Community/DragonOS, pull requests merged in 2025-08, with the labels that each got.

#1246 feat: implement basic mount namespace support
  kernel/src/driver/tty/pty/unix98pty.rs
  kernel/src/filesystem/devfs/mod.rs
  kernel/src/filesystem/fs.rs
  kernel/src/filesystem/overlayfs/mod.rs
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/sysfs/mod.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/syscall/mod.rs
  kernel/src/filesystem/vfs/syscall/sys_mount.rs
  kernel/src/filesystem/vfs/syscall/sys_umount2.rs
  kernel/src/filesystem/vfs/utils.rs
  kernel/src/filesystem/vfs/vcore.rs
  kernel/src/process/namespace/mnt.rs
  kernel/src/process/namespace/mod.rs
  kernel/src/process/namespace/nsproxy.rs
  kernel/src/process/stdio.rs
Labels: enhancement

#1250 feat: support fsync/sync/syncfs syscall
  kernel/src/filesystem/page_cache.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/syscall/mod.rs
  kernel/src/filesystem/vfs/syscall/sys_fsync.rs
  kernel/src/filesystem/vfs/syscall/sys_sync.rs
Labels: enhancement

#1249 fix: Fixed several errors in the file system
  kernel/src/bpf/map/mod.rs
  kernel/src/bpf/prog/mod.rs
  kernel/src/driver/base/block/gendisk/mod.rs
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/clocksource/acpi_pm.rs
  kernel/src/driver/input/ps2_mouse/ps_mouse_device.rs
  kernel/src/driver/keyboard/ps2_keyboard.rs
  kernel/src/driver/tty/tty_device.rs
  kernel/src/driver/video/fbdev/base/fbmem.rs
  kernel/src/filesystem/devfs/mod.rs
  kernel/src/filesystem/devfs/null_dev.rs
  kernel/src/filesystem/devfs/zero_dev.rs
  kernel/src/filesystem/devpts/mod.rs
  kernel/src/filesystem/epoll/fs.rs
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/open.rs
  kernel/src/filesystem/vfs/vcore.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/ipc/pipe.rs
  kernel/src/net/socket/mod.rs
  kernel/src/perf/bpf.rs
  kernel/src/perf/kprobe.rs
  kernel/src/perf/mod.rs
  kernel/src/perf/tracepoint.rs
  kernel/src/virt/vm/kvm_dev.rs
Labels: Bug fix

#1255 feat: add set/getgroups syscall
  kernel/src/process/cred.rs
  kernel/src/process/syscall/mod.rs
  kernel/src/process/syscall/sys_groups.rs
Labels: enhancement

#1253 feat(filesystem): 添加MountFlags支持并实现`/proc/mounts`文件
  kernel/src/filesystem/devfs/mod.rs
  kernel/src/filesystem/devpts/mod.rs
  kernel/src/filesystem/kernfs/mod.rs
  kernel/src/filesystem/procfs/mod.rs
  kernel/src/filesystem/procfs/proc_mounts.rs
  kernel/src/filesystem/sysfs/mod.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/syscall/sys_mount.rs
  kernel/src/filesystem/vfs/vcore.rs
  kernel/src/process/namespace/mnt.rs
Labels: enhancement

#1270 remove bad include
  user/apps/c_unitest/test_cross_process_futex.c
Labels: ambiguous
