Repository DragonOS-Community/DragonOS, pull requests merged in 2025-09, with the labels that each got.

#1276 fix(futex): 修复futex键不存在时的错误处理
  kernel/src/libs/futex/futex.rs
Labels: Bug fix

#1279 refactor: Add system call number to name conversion
  kernel/Makefile
  kernel/src/arch/loongarch64/syscall/nr.rs
  kernel/src/arch/riscv64/syscall/nr.rs
  kernel/src/arch/x86_64/syscall/nr.rs
  kernel/src/driver/tty/pty/mod.rs
  kernel/src/driver/tty/pty/unix98pty.rs
  kernel/src/driver/tty/tty_core.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/filesystem/epoll/event_poll.rs
  kernel/src/filesystem/poll.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/syscall/sys_fcntl.rs
  kernel/src/mm/allocator/kernel_allocator.rs
  kernel/src/syscall/mod.rs
  user/apps/c_unitest/ptmx_demo.c
  user/apps/c_unitest/test_pty.c
  user/apps/c_unitest/test_stdin.c
  user/apps/c_unitest/tty_demo.c
Labels: test

#1288 feat(ipc): 实现IPC命名空间初步支持
  docs/kernel/ipc/index.rst
  docs/kernel/ipc/ipc_namespace.md
  kernel/src/ipc/shm.rs
  kernel/src/ipc/syscall/sys_shmat.rs
  kernel/src/ipc/syscall/sys_shmctl.rs
  kernel/src/ipc/syscall/sys_shmget.rs
  kernel/src/mm/init.rs
  kernel/src/mm/page.rs
  kernel/src/mm/ucontext.rs
  kernel/src/process/namespace/ipc_namespace.rs
  kernel/src/process/namespace/mod.rs
  kernel/src/process/namespace/nsproxy.rs
  user/apps/r_unitest/Cargo.lock
  user/apps/r_unitest/src/bin/test_ipc_ns_shm.rs
Labels: enhancement

#1258 feat(syscall/mincore):实现了mincore系统调用
  kernel/src/mm/mincore.rs
  kernel/src/mm/mod.rs
  kernel/src/mm/syscall/sys_mincore.rs
  kernel/src/mm/ucontext.rs
  user/apps/c_unitest/test_mincore.c
Labels: enhancement

#1292 docs: 添加腾讯云EdgeOne作为CDN赞助商
  README.md
  README_CN.md
Labels: documentation

#1296 test(gvisor): add chdir_test and fix test runner filter formatting
  user/apps/tests/syscall/gvisor/blocklists/chdir_test
  user/apps/tests/syscall/gvisor/runner/src/lib_sync.rs
  user/apps/tests/syscall/gvisor/whitelist.txt
Labels: test
