Repository DragonOS-Community/DragonOS, pull requests merged in 2025-06, with the labels that each got.

#1189 fix: 解决创建buddy的函数栈帧过大的问题
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/src/arch/x86_64/smp/mod.rs
  kernel/src/mm/allocator/buddy.rs
  kernel/src/mm/no_init.rs
Labels: Bug fix

#1205 fix(net): 解决dhcp偶尔失败的问题
  kernel/src/net/net_core.rs
Labels: Bug fix

#1204 fix(time): 处理信号中断导致的定时器唤醒
  kernel/src/time/sleep.rs
  kernel/src/time/timer.rs
Labels: Bug fix

#1206 fix: 检测不到ctrl+D的问题 && pid=1被kill的时候没报错的问题
  kernel/crates/bitmap/src/traits.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/process/mod.rs
Labels: Bug fix

#1190 feat: support tracepoint-based ebpf programs
  docs/kernel/trace/index.rst
  docs/kernel/trace/tracepoint.md
  kernel/src/bpf/helper/consts.rs
  kernel/src/bpf/helper/mod.rs
  kernel/src/debug/tracing/mod.rs
  kernel/src/debug/tracing/trace_pipe.rs
  kernel/src/filesystem/kernfs/callback.rs
  kernel/src/filesystem/vfs/syscall/open_utils.rs
  kernel/src/perf/mod.rs
  kernel/src/perf/tracepoint.rs
  kernel/src/perf/util.rs
  kernel/src/tracepoint/basic_macro.rs
  kernel/src/tracepoint/mod.rs
  kernel/src/tracepoint/point.rs
  kernel/src/tracepoint/trace_pipe.rs
  user/apps/test_tracepoint/.gitignore
  user/apps/test_tracepoint/Cargo.lock
  user/apps/test_tracepoint/Cargo.toml
  user/apps/test_tracepoint/Makefile
  user/apps/test_tracepoint/README.md
  user/apps/test_tracepoint/mytrace-common/Cargo.toml
  user/apps/test_tracepoint/mytrace-common/src/lib.rs
  user/apps/test_tracepoint/mytrace-ebpf/Cargo.toml
  user/apps/test_tracepoint/mytrace-ebpf/build.rs
  user/apps/test_tracepoint/mytrace-ebpf/src/lib.rs
  user/apps/test_tracepoint/mytrace-ebpf/src/main.rs
  user/apps/test_tracepoint/mytrace/Cargo.toml
  user/apps/test_tracepoint/mytrace/build.rs
  user/apps/test_tracepoint/mytrace/src/main.rs
  user/apps/test_tracepoint/rustfmt.toml
  user/dadk/config/test_tracepoint.toml
Labels: enhancement

#1176 feat: debug kernel stack
  kernel/Cargo.toml
  kernel/src/arch/loongarch64/mm/mod.rs
  kernel/src/arch/riscv64/mm/mod.rs
  kernel/src/arch/x86_64/mm/fault.rs
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/init/cmdline.rs
  kernel/src/libs/elf.rs
  kernel/src/mm/mmio_buddy.rs
  kernel/src/mm/mod.rs
  kernel/src/process/execve.rs
  kernel/src/process/mod.rs
  kernel/src/syscall/user_access.rs
Labels: enhancement

#1209 feat: Update rbpf to mainline
  .github/workflows/makefile.yml
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/Makefile
  kernel/crates/rbpf/.appveyor.yml
  kernel/crates/rbpf/.gitignore
  kernel/crates/rbpf/Cargo.toml
  kernel/crates/rbpf/LICENSE-APACHE
  kernel/crates/rbpf/LICENSE-MIT
  kernel/crates/rbpf/README.md
  kernel/crates/rbpf/clippy.toml
  kernel/crates/rbpf/examples/disassemble.rs
  kernel/crates/rbpf/examples/helper.rs
  kernel/crates/rbpf/examples/load_elf.rs
  kernel/crates/rbpf/examples/load_elf__block_a_port.c
  kernel/crates/rbpf/examples/rbpf_plugin.rs
  kernel/crates/rbpf/examples/to_json.rs
  kernel/crates/rbpf/examples/uptime.rs
  kernel/crates/rbpf/mk/appveyor.bat
  kernel/crates/rbpf/rustfmt.toml
  kernel/crates/rbpf/src/asm_parser.rs
  kernel/crates/rbpf/src/assembler.rs
  kernel/crates/rbpf/src/cranelift.rs
  kernel/crates/rbpf/src/disassembler.rs
  kernel/crates/rbpf/src/ebpf.rs
  kernel/crates/rbpf/src/helpers.rs
  kernel/crates/rbpf/src/insn_builder.rs
  kernel/crates/rbpf/src/interpreter.rs
  kernel/crates/rbpf/src/jit.rs
  kernel/crates/rbpf/src/lib.rs
  kernel/crates/rbpf/src/no_std_error.rs
  kernel/crates/rbpf/src/stack.rs
  kernel/crates/rbpf/src/verifier.rs
  kernel/crates/rbpf/tests/assembler.rs
  kernel/crates/rbpf/tests/common.rs
  kernel/crates/rbpf/tests/cranelift.rs
  kernel/crates/rbpf/tests/disassembler.rs
  kernel/crates/rbpf/tests/misc.rs
  kernel/crates/rbpf/tests/ubpf_jit_x86_64.rs
  kernel/crates/rbpf/tests/ubpf_verifier.rs
  kernel/crates/rbpf/tests/ubpf_vm.rs
  kernel/src/perf/kprobe.rs
  kernel/src/perf/mod.rs
  kernel/src/perf/tracepoint.rs
  triagebot.toml
Labels: enhancement

#1182 feat(fs): 补充mount系统调用，增加对硬盘挂载 & ext4文件系统的支持
  docs/kernel/filesystem/vfs/index.rst
  docs/kernel/filesystem/vfs/mountable_fs.md
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/crates/kdepends/Cargo.toml
  kernel/crates/kdepends/src/lib.rs
  kernel/crates/system_error/Cargo.toml
  kernel/crates/system_error/src/another_ext4.rs
  kernel/crates/system_error/src/lib.rs
  kernel/src/driver/base/block/gendisk/mod.rs
  kernel/src/driver/base/block/manager.rs
  kernel/src/driver/base/device/device_number.rs
  kernel/src/driver/base/device/mod.rs
  kernel/src/driver/block/virtio_blk.rs
  kernel/src/driver/disk/ahci/ahcidisk.rs
  kernel/src/driver/virtio/virtio.rs
  kernel/src/filesystem/devfs/mod.rs
  kernel/src/filesystem/devpts/mod.rs
  kernel/src/filesystem/ext4/filesystem.rs
  kernel/src/filesystem/ext4/gendisk.rs
  kernel/src/filesystem/ext4/inode.rs
  kernel/src/filesystem/ext4/mod.rs
  kernel/src/filesystem/fat/mod.rs
  kernel/src/filesystem/fat/mount.rs
  kernel/src/filesystem/mod.rs
  kernel/src/filesystem/overlayfs/mod.rs
  kernel/src/filesystem/ramfs/mod.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/filesystem/vfs/syscall/mod.rs
  kernel/src/filesystem/vfs/syscall/symlink_utils.rs
  kernel/src/filesystem/vfs/syscall/sys_mount.rs
  kernel/src/filesystem/vfs/syscall/sys_symlink.rs
  kernel/src/filesystem/vfs/syscall/sys_symlinkat.rs
  kernel/src/filesystem/vfs/syscall/sys_umount2.rs
  kernel/src/filesystem/vfs/vcore.rs
  kernel/src/syscall/mod.rs
  tools/make_fs_image.sh
  tools/run-qemu.sh
  user/apps/test-mount-ext4/.gitignore
  user/apps/test-mount-ext4/Cargo.toml
  user/apps/test-mount-ext4/Makefile
  user/apps/test-mount-ext4/src/main.rs
  user/apps/test-mount-fat/.gitignore
  user/apps/test-mount-fat/Cargo.toml
  user/apps/test-mount-fat/Makefile
  user/apps/test-mount-fat/src/main.rs
  user/dadk/config/test_mount_ext4_0_1_0.toml
  user/dadk/config/test_mount_fat_0_1_0.toml
Labels: enhancement, A-fs

#1224 Fix mountable fs doc
  docs/kernel/filesystem/vfs/mountable_fs.md
  tools/doc_translator.py
Labels: ambiguous
