Repository DragonOS-Community/DragonOS, pull requests merged in 2025-04, with the labels that each got.

#1123 fix the panic error for riscv64
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/Makefile
  kernel/crates/intertrait/src/lib.rs
  kernel/src/arch/riscv64/mod.rs
  kernel/src/arch/riscv64/syscall/mod.rs
  kernel/src/arch/x86_64/mod.rs
  kernel/src/arch/x86_64/syscall/mod.rs
  kernel/src/debug/kallsyms.c
  kernel/src/debug/panic/hook.rs
  kernel/src/debug/panic/mod.rs
  kernel/src/debug/traceback/mod.rs
  kernel/src/lib.rs
  kernel/src/mm/allocator/kernel_allocator.rs
  kernel/src/syscall/mod.rs
Labels: ambiguous

#1127 feat: 实现ppoll系统调用并优化poll相关功能
  kernel/src/filesystem/poll.rs
  kernel/src/ipc/signal.rs
  kernel/src/ipc/signal_types.rs
  kernel/src/ipc/syscall.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/process/mod.rs
  kernel/src/syscall/mod.rs
  kernel/src/time/mod.rs
  user/apps/test_poll/.gitignore
  user/apps/test_poll/Makefile
  user/apps/test_poll/ppoll.c
Labels: enhancement

#1129 fix(build): filter out mislinked debug symbol in the first link stage
  kernel/src/Makefile
Labels: Bug fix

#1130 feat(net): 引入kthread，将Inet-网卡处理流程移入内核线程中
  kernel/src/driver/net/irq_handle.rs
  kernel/src/driver/net/kthread.rs
  kernel/src/driver/net/mod.rs
  kernel/src/driver/net/virtio_net.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
Labels: enhancement, A-network

#1128 refactor epoll related implementation
  kernel/Cargo.toml
  kernel/src/driver/tty/tty_core.rs
  kernel/src/driver/tty/tty_device.rs
  kernel/src/filesystem/eventfd.rs
  kernel/src/filesystem/vfs/file.rs
  kernel/src/filesystem/vfs/mod.rs
  kernel/src/filesystem/vfs/mount.rs
  kernel/src/ipc/pipe.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/net/socket/mod.rs
  kernel/src/perf/mod.rs
  user/apps/syscall_ebpf/syscall_ebpf-ebpf/rust-toolchain.toml
  user/apps/test_epoll/.gitignore
  user/apps/test_epoll/Makefile
  user/apps/test_epoll/main.c
  user/dadk/config/test_epoll.toml
Labels: ambiguous

#1134 fix: la64 ci
  .github/workflows/makefile.yml
  build-scripts/kernel_build/src/cfiles/mod.rs
  tools/BUILD_CONTAINER_VERSION
  tools/bootstrap.sh
  tools/build_in_docker.sh
Labels: Bug fix

#1088 feat:Add tracepoint prototype
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/src/arch/loongarch64/link.ld
  kernel/src/arch/riscv64/link.ld
  kernel/src/arch/x86_64/link.lds
  kernel/src/debug/.gitignore
  kernel/src/debug/mod.rs
  kernel/src/debug/sysfs/mod.rs
  kernel/src/debug/tracing/events.rs
  kernel/src/debug/tracing/mod.rs
  kernel/src/debug/tracing/trace_pipe.rs
  kernel/src/debug/tracing/tracepoint.rs
  kernel/src/filesystem/kernfs/callback.rs
  kernel/src/filesystem/vfs/core.rs
Labels: enhancement

#1115 Feat(process): 增加ProcessGroup以及Session机制
  Makefile
  docs/community/contact/index.rst
  docs/introduction/build_system.md
  kernel/src/arch/x86_64/ipc/signal.rs
  kernel/src/driver/tty/tty_job_control.rs
  kernel/src/driver/tty/tty_ldisc/ntty.rs
  kernel/src/ipc/syscall.rs
  kernel/src/process/exit.rs
  kernel/src/process/fork.rs
  kernel/src/process/mod.rs
  kernel/src/process/process_group.rs
  kernel/src/process/session.rs
  kernel/src/process/syscall.rs
  kernel/src/syscall/mod.rs
  user/apps/test-processgroup/.gitignore
  user/apps/test-processgroup/Makefile
  user/apps/test-processgroup/main.c
  user/apps/test-session/.gitignore
  user/apps/test-session/Makefile
  user/apps/test-session/main.c
  user/dadk/config/test_processgroup_0_1_0.toml
  user/dadk/config/test_session_0_1_0.toml
Labels: enhancement, ambiguous

#1144 fix(tools): 调整bootstrap.sh脚本中的banner和依赖安装顺序
  tools/bootstrap.sh
Labels: Bug fix
