Repository DragonOS-Community/DragonOS, pull requests merged in 2025-03, with the labels that each got.

#1087 fix(net): Unix 资源释放
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/mod.rs
  user/apps/test_unix_stream_socket/src/main.rs
Labels: good first issue, Done, Bug fix

#1091 fix: 在插入新的timer时,边界条件判断不正确的问题
  .gitignore
  kernel/src/time/timer.rs
Labels: Bug fix, S-等待审查

#1096 fix(net): misc of resources release
  kernel/Cargo.toml
  kernel/src/driver/net/loopback.rs
  kernel/src/driver/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/common/shutdown.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/datagram/inner.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/mod.rs
  user/apps/test_unix_stream_socket/src/main.rs
Labels: Bug fix

#1099 feat(net): Add Internet protocol socket documents
  docs/kernel/net/index.rst
  docs/kernel/net/inet.md
Labels: enhancement, S-等待审查, T-doc

#1090 fix:修复epoll_pwait部分与linux不一致的行为
  kernel/src/ipc/signal.rs
  kernel/src/net/event_poll/syscall.rs
  kernel/src/process/mod.rs
Labels: Bug fix, S-等待审查

#1100 chore: 删除package-lock.json并恢复.gdbinit配置文件
  package-lock.json
  tools/.gdbinit
Labels: S-等待审查

#1106 fix: permission problems in container
  .vscode/settings.json
  Makefile
  dadk-manifest.toml
  env.mk
  oscomp/run-qemu.sh
Labels: Bug fix, S-等待审查

#1109 feat:make fmt
  kernel/src/namespaces/syscall.rs
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
Labels: enhancement

#1112 fix: 修复nttyData的buffer导致初始化时,栈溢出的问题
  kernel/src/driver/tty/tty_ldisc/ntty.rs
Labels: Bug fix

#1111 fix: 修复slab分配器的UAF\内存越界问题
  kernel/crates/rust-slabmalloc/src/lib.rs
  kernel/crates/rust-slabmalloc/src/pages.rs
  kernel/crates/rust-slabmalloc/src/sc.rs
  kernel/crates/rust-slabmalloc/src/tests.rs
  kernel/crates/rust-slabmalloc/src/zone.rs
  kernel/src/mm/allocator/kernel_allocator.rs
  kernel/src/mm/allocator/slab.rs
Labels: Bug fix

#1110 feat:fmt
  kernel/src/net/socket/buffer.rs
  kernel/src/net/socket/unix/seqpacket/inner.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
  kernel/src/net/socket/unix/stream/inner.rs
  kernel/src/net/socket/unix/stream/mod.rs
Labels: enhancement

#1093 feat(kvm): 删除了旧版本kvm的代码
  kernel/Cargo.toml
  kernel/src/arch/x86_64/kvm/mod.rs
  kernel/src/arch/x86_64/kvm/vmx/ept.rs
  kernel/src/arch/x86_64/kvm/vmx/kvm_emulation.rs
  kernel/src/arch/x86_64/kvm/vmx/mmu.rs
  kernel/src/arch/x86_64/kvm/vmx/mod.rs
  kernel/src/arch/x86_64/kvm/vmx/seg.rs
  kernel/src/arch/x86_64/kvm/vmx/vcpu.rs
  kernel/src/arch/x86_64/kvm/vmx/vmcs.rs
  kernel/src/arch/x86_64/kvm/vmx/vmexit.rs
  kernel/src/arch/x86_64/kvm/vmx/vmx_asm_wrapper.rs
  kernel/src/arch/x86_64/mm/mod.rs
  kernel/src/arch/x86_64/mod.rs
  kernel/src/arch/x86_64/vm/mmu/kvm_mmu.rs
  kernel/src/arch/x86_64/vm/mmu/mmu_internal.rs
  kernel/src/arch/x86_64/vm/vmx/ept/mod.rs
  kernel/src/virt/mod.rs
  kernel/src/virt/vm/kvm_host/mem.rs
  kernel/src/virt/vm/kvm_host/mod.rs
  kernel/src/virt/vm/kvm_host/vcpu.rs
Labels: enhancement

#1116 fix: remove useless c code
  docs/kernel/core_api/kernel_api.md
  kernel/Cargo.lock
  kernel/Cargo.toml
  kernel/src/common/kprint.h
  kernel/src/common/printk.h
  kernel/src/common/stdio.h
  kernel/src/debug/Makefile
  kernel/src/debug/kprobe/args.rs
  kernel/src/debug/mod.rs
  kernel/src/debug/panic/hook.rs
  kernel/src/debug/panic/mod.rs
  kernel/src/debug/traceback/mod.rs
  kernel/src/debug/traceback/traceback.c
  kernel/src/debug/traceback/traceback.h
  kernel/src/lib.rs
  kernel/src/libs/printk.c
  user/apps/test_ebpf/Cargo.lock
  user/apps/test_ebpf/syscall_ebpf/Cargo.lock
  user/apps/test_ebpf/syscall_ebpf/syscall_ebpf-ebpf/Cargo.lock
Labels: Bug fix

#1124 fix: 修复elf加载器在读取解释器路径时的越界问题
  kernel/src/libs/elf.rs
Labels: Bug fix

#1125 feat: 支持在rv64下，运行rust编写的helloworld程序
  .github/workflows/makefile.yml
  kernel/Cargo.lock
  kernel/src/arch/riscv64/interrupt/handle.rs
  kernel/src/driver/irqchip/riscv_sifive_plic.rs
  kernel/src/init/cmdline.rs
  kernel/src/init/initial_kthread.rs
  kernel/src/syscall/mod.rs
  tools/BUILD_CONTAINER_VERSION
  tools/bootstrap.sh
  tools/build_in_docker.sh
  tools/run-qemu.sh
  user/apps/riscv_init/Makefile
  user/apps/riscv_init/riscv_rust_init/.cargo/config.toml
  user/apps/riscv_init/riscv_rust_init/.gitignore
  user/apps/riscv_init/riscv_rust_init/Cargo.toml
  user/apps/riscv_init/riscv_rust_init/Makefile
  user/apps/riscv_init/riscv_rust_init/src/main.rs
Labels: enhancement
