Repository DragonOS-Community/DragonOS, pull requests merged in 2025-01, with the labels that each got.

#1080 fix: 修复wait4系统调用部分语义与Linux不一致的问题
  kernel/src/driver/tty/tty_job_control.rs
  kernel/src/filesystem/eventfd.rs
  kernel/src/libs/semaphore.rs
  kernel/src/libs/wait_queue.rs
  kernel/src/net/event_poll/mod.rs
  kernel/src/process/exit.rs
  kernel/src/process/mod.rs
  kernel/src/sched/completion.rs
  user/dadk/config/nova_shell-0.1.0.toml
Labels: Bug fix, S-等待审查, A-driver, A-fs

#1081 feat(fs/syscall): 实现fchdir系统调用
  kernel/src/filesystem/vfs/syscall.rs
  kernel/src/syscall/mod.rs
Labels: enhancement, A-fs

#1082 fix: 修正nographic启动时,控制台日志未能输出到文件的问题
  tools/run-qemu.sh
Labels: Bug fix

#1085 fix: TCP socket miss activation after close
  kernel/src/driver/net/mod.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/common/shutdown.rs
  kernel/src/net/socket/inet/common/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
Labels: Bug fix, A-network

#1086 fix: loopback and udp resource problem
  kernel/Cargo.toml
  kernel/src/driver/net/loopback.rs
  kernel/src/net/net_core.rs
  kernel/src/net/socket/inet/datagram/inner.rs
  kernel/src/net/socket/inet/datagram/mod.rs
  kernel/src/net/socket/inet/stream/inner.rs
  kernel/src/net/socket/inet/stream/mod.rs
  kernel/src/net/socket/unix/seqpacket/mod.rs
Labels: Bug fix
